# SPDX-License-Identifier: Apache-2.0
# Cargo layout that compiles the upstream inc_diagnostics sources of PR #40 (d388985) in place.
# Mirrors the Bazel targets of score/mw/diag/api, score/mw/diag/sovd_adapter and score/opensovd-gateway.
[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
opensovd-core = { git = "https://github.com/eclipse-opensovd/opensovd-core.git", rev = "29e806f3226cbce5fb9985924de737d8e3fb6a47" }
opensovd-server = { git = "https://github.com/eclipse-opensovd/opensovd-core.git", rev = "29e806f3226cbce5fb9985924de737d8e3fb6a47" }
