#!/usr/bin/env python3
# Copyright (c) 2026 Eclipse SDV Hackathon Team
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).
# The AI-generated portions may be considered public domain (CC0-1.0).
# Human provenance review and verification are pending.
#
# SPDX-License-Identifier: Apache-2.0 AND CC0-1.0

"""Operate the dedicated loop4 Fabro server without exposing authentication."""
import hashlib
import json
from pathlib import Path
import sys
import urllib.error
import urllib.request

PACKAGE = Path(__file__).resolve().parent
ARTIFACTS = PACKAGE.parent / "artifacts"
STORE = Path("/media/jefferson/11c42dee-73a3-4c2b-ab42-a0440011d9e0/threadx-contributions/fabro-storage")
SERVER = "http://127.0.0.1:32277/api/v1"


def request(path, payload=None):
    values = dict(line.split("=", 1) for line in (STORE / "server.env").read_text().splitlines() if "=" in line)
    req = urllib.request.Request(SERVER + path,
        data=None if payload is None else json.dumps(payload).encode(),
        headers={"Authorization": "Bearer " + values["FABRO_DEV_TOKEN"], "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=60) as response:
            body = response.read()
            return json.loads(body) if body else {"status": "accepted"}
    except urllib.error.HTTPError as error:
        body = error.read().decode()
        raise RuntimeError(f"Fabro HTTP {error.code}: {body[:1500]}") from None


def save(name, value):
    ARTIFACTS.mkdir(exist_ok=True)
    (ARTIFACTS / name).write_text(json.dumps(value, indent=2) + "\n")


def register(entrypoint="workflow.fabro"):
    files = {str(p.relative_to(PACKAGE)): p.read_text() for p in PACKAGE.rglob("*")
             if p.is_file() and p.suffix in [".md", ".py", ".toml", ".fabro"]}
    files["Dockerfile"] = (PACKAGE / "Dockerfile").read_text()
    # The registered graph executes these immutable copies, never live workspace
    # prompts or driver code that can change while a run is waiting for review.
    execution = {name: content for name, content in files.items()
                 if name == "Dockerfile" or Path(name).suffix in [".py", ".toml", ".fabro"]
                 or name.startswith("prompts/")}
    execution["regression-design.md"] = (PACKAGE.parent / "regression-design.md").read_text()
    hashes = {name: hashlib.sha256(content.encode()).hexdigest() for name, content in execution.items()}
    digest = hashlib.sha256(json.dumps(hashes, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    bundle = STORE.parent / "executions" / digest
    image = "sha256:a8a3d92ee0ba622304a79ce1dcc51aba1ad1d0ac52767c71b7c1e158520275cc"
    manifest = {"bundle_sha256": digest, "files": hashes, "image_id": image}
    if not bundle.exists():
        bundle.mkdir(parents=True)
        for name, content in execution.items():
            target = bundle / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
            target.chmod(0o444)
        (bundle / "execution-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
        (bundle / "execution-manifest.json").chmod(0o444)
        for directory in sorted((p for p in bundle.rglob("*") if p.is_dir()), reverse=True):
            directory.chmod(0o555)
        bundle.chmod(0o555)
    for name, expected in hashes.items():
        if hashlib.sha256((bundle / name).read_bytes()).hexdigest() != expected:
            raise RuntimeError("Existing immutable bundle was modified: " + name)
    if json.loads((bundle / "execution-manifest.json").read_text()) != manifest:
        raise RuntimeError("Existing execution manifest changed")
    for name in files:
        if name.endswith(".fabro"):
            files[name] = files[name].replace(str(PACKAGE / "driver.py"), str(bundle / "driver.py"))
    files["execution-manifest.json"] = json.dumps(manifest, indent=2) + "\n"
    files["regression-design.md"] = execution["regression-design.md"]
    version = request("/workflow-versions", {"entrypoint": entrypoint, "files": files, "workflow_dependencies": {}})
    save("execution-binding.json", {**manifest, "bundle_path": str(bundle), **version})
    return version


def launch(mode="full"):
    entrypoints = {"full": "workflow.fabro", "resume": "resume/workflow.fabro",
                   "verify": "resume-verify/workflow.fabro", "docs": "docs/workflow.fabro",
                   "validated": "resume-validated/workflow.fabro", "monitor": "monitor/workflow.fabro", "publish": "publish/workflow.fabro"}
    monitor_binding = ARTIFACTS / "monitor-execution-binding.json"
    if mode == "monitor" and monitor_binding.exists():
        # Keep monitoring published patches with their measured immutable runner.
        binding = json.loads(monitor_binding.read_text())
        bundle = Path(binding["bundle_path"])
        verification = json.loads((STORE.parent / "744/evidence/verification.json").read_text())
        for name, expected in binding["files"].items():
            if hashlib.sha256((bundle / name).read_bytes()).hexdigest() != expected:
                raise RuntimeError("Published monitor bundle changed: " + name)
        if binding["files"]["driver.py"] != verification["driver_sha256"]:
            raise RuntimeError("Monitor runner does not match the published patch verification")
        version = {"workflow_version_id": binding["workflow_version_id"]}
        save("execution-binding.json", binding)
    else:
        version = register(entrypoints[mode])
        if mode == "monitor":
            save("monitor-execution-binding.json", json.loads((ARTIFACTS / "execution-binding.json").read_text()))
    prefix = "docs-" if mode == "docs" else ""
    save(prefix + "workflow-version.json", version)
    run = request("/runs", {"workflow_version_id": version["workflow_version_id"],
          "target": {"kind": "folder", "path": "/media/jefferson/11c42dee-73a3-4c2b-ab42-a0440011d9e0/threadx-contributions/744/" + ("docs-source" if mode == "docs" else "source")},
          "environment_id": "local", "title": "ThreadX #744 — Codex Sol 6.1 High contribution",
          "args": {"labels": {"project": "eclipse-threadx", "issue": "744", "model": "gpt-6.1-sol", "reasoning": "high", "storage": "loop4"}}})
    save(prefix + "fabro-run-created.json", run)
    run_id = run.get("id", run.get("run_id"))
    started = request("/runs/" + run_id + "/start", {})
    save(prefix + "fabro-run-started.json", started)
    print(json.dumps({"run_id": run_id, "workflow_version_id": version["workflow_version_id"], "server": SERVER}))


if __name__ == "__main__":
    if sys.argv[1] == "launch":
        launch(sys.argv[2] if len(sys.argv) > 2 else "full")
    elif sys.argv[1] == "register":
        version = register()
        save("workflow-final-version.json", version)
        print(json.dumps(version))
    else:
        run = json.loads((ARTIFACTS / "fabro-run-created.json").read_text())
        run_id = run.get("id", run.get("run_id"))
        result = request("/runs/" + run_id)
        save("fabro-run-status.json", result)
        print(json.dumps(result, indent=2))
