# Copyright (c) 2026 Eclipse SDV Hackathon Team
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).
# The AI-generated portions may be considered public domain (CC0-1.0).
# Human provenance review and verification are pending.
#
# SPDX-License-Identifier: Apache-2.0 AND CC0-1.0

"""A baseline failure permits draft preparation only with exact reproduction."""
import copy
import unittest
from unittest.mock import patch

import driver


class BaselineClassificationTests(unittest.TestCase):
    def record(self):
        proof = {"status": "failed-on-candidate-and-unchanged-baseline", "base_sha": "base",
                 "patch_sha256": "patch", "image_id": driver.IMAGE, "host_cpus": [0, 2, 4, 6],
                 "unchanged_inputs": ["common_smp", "ports_smp", "test/smp", "test/shared", "test/tx/regression", "cmake", "scripts"],
                 "candidate_failures": [{"test": "trace_build::threadx_smp_random_resume_suspend_exclusion_pt_test", "assertion": "ERROR #7"}],
                 "baseline_runs": [{"configuration": "trace_build", "exit_code": 1}]}
        record = {"status": "prepared-with-baseline-failure", "local_validation_complete": False,
                  "smp_host_cpus": [0, 2, 4, 6], "checks": []}
        for name in ["baseline", "focused", "tx", "smp", "freertos", "ai-disclosure", "port-consistency", "license-headers"]:
            record["checks"].append({"name": name, "status": "expected-failure" if name == "baseline" else "pass"})
        record["checks"][3].update({"status": "baseline-failure", "baseline_reproduction": proof})
        return record

    def prepared(self, record):
        with patch.object(driver, "base", return_value="base"), patch.object(driver, "patch_hash", return_value="patch"):
            return driver.verification_prepared(record)

    def test_disclosed_matching_baseline_failure_permits_only_preparation(self):
        record = self.record()
        self.assertTrue(self.prepared(record))
        self.assertFalse(record["local_validation_complete"])
        self.assertEqual(record["checks"][3]["status"], "baseline-failure")

    def test_no_baseline_failure_or_wrong_configuration_is_rejected(self):
        for runs in [[], [{"configuration": "trace_build", "exit_code": 0}], [{"configuration": "default_build_coverage", "exit_code": 1}]]:
            record = self.record()
            record["checks"][3]["baseline_reproduction"]["baseline_runs"] = runs
            self.assertFalse(self.prepared(record))

    def test_other_local_failures_are_never_waived(self):
        for name in ["focused", "tx", "freertos", "ai-disclosure", "port-consistency", "license-headers"]:
            record = self.record()
            next(c for c in record["checks"] if c["name"] == name)["status"] = "fail"
            self.assertFalse(self.prepared(record))

    def test_different_patch_base_image_or_cpu_profile_is_rejected(self):
        for field in ["patch_sha256", "base_sha", "image_id", "host_cpus", "unchanged_inputs"]:
            record = self.record()
            record["checks"][3]["baseline_reproduction"][field] = "different"
            self.assertFalse(self.prepared(record))

    def test_other_assertions_and_tests_cannot_use_this_classification(self):
        for field in ["assertion", "test"]:
            record = self.record()
            record["checks"][3]["baseline_reproduction"]["candidate_failures"][0][field] = "different"
            self.assertFalse(self.prepared(record))

    def test_top_level_pass_cannot_hide_failed_or_missing_checks(self):
        record = self.record()
        record["status"] = "pass"
        self.assertFalse(self.prepared(record))
        record["checks"] = []
        self.assertFalse(self.prepared(record))


if __name__ == "__main__":
    unittest.main()
