# Copyright (c) 2026 Eclipse SDV Hackathon Team
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).
# The AI-generated portions may be considered public domain (CC0-1.0).
# Human provenance review and verification are pending.
#
# SPDX-License-Identifier: Apache-2.0 AND CC0-1.0

"""Checks for false-positive review acceptance and external readiness claims."""
import json
import io
import hashlib
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch

import driver
import record_conversation_review


class ReviewGateTests(unittest.TestCase):
    def records(self, digest="current", technical="pass", process="pass"):
        return {
            "freeze.json": {"patch_sha256": "current"},
            "verification.json": {"patch_sha256": "current", "status": "pass", "checks": [
                {"name": name, "status": "expected-failure" if name == "baseline" else "pass"}
                for name in ["baseline", "focused", "tx", "smp", "freertos", "ai-disclosure", "port-consistency", "license-headers"]]},
            "technical-review.json": {"patch_sha256": digest, "verdict": technical, "findings": []},
            "process-review.json": {"patch_sha256": "current", "verdict": process, "findings": []},
            "docs-verification.json": {"patch_sha256": "docs", "status": "pass"},
            "documentation-review.json": {"patch_sha256": "docs", "verdict": "pass", "findings": []},
        }

    def check(self, records):
        with patch.object(driver, "read", side_effect=records.__getitem__), \
             patch.object(driver, "patch_hash", return_value="current"), \
             patch.object(driver, "docs_hash", return_value="docs"), \
             patch.object(driver, "consent_ready", return_value=False), \
             patch.object(driver, "write"):
            driver.review_gate()

    def test_stale_approval_cannot_accept_a_new_patch(self):
        with self.assertRaises(RuntimeError):
            self.check(self.records(digest="old-reviewed-patch"))

    def test_failed_independent_review_blocks_publication(self):
        with self.assertRaises(RuntimeError):
            self.check(self.records(process="fail"))

    def test_missing_or_failed_license_audit_cannot_be_waived_by_reviews(self):
        for missing in [False, True]:
            records = self.records()
            if missing:
                records["verification.json"]["checks"] = [
                    item for item in records["verification.json"]["checks"]
                    if item["name"] != "license-headers"]
            else:
                next(item for item in records["verification.json"]["checks"]
                     if item["name"] == "license-headers")["status"] = "fail"
            with self.assertRaises(RuntimeError):
                self.check(records)

    def test_failed_measured_verification_overrides_agent_passes(self):
        records = self.records()
        records["verification.json"]["status"] = "fail"
        with self.assertRaises(RuntimeError):
            self.check(records)

    def test_blocking_finding_overrides_a_pass_verdict(self):
        records = self.records()
        records["technical-review.json"]["findings"] = [{"severity": "high", "message": "Stack pointer still truncates"}]
        with self.assertRaises(RuntimeError):
            self.check(records)

    def test_stale_companion_review_blocks_publication(self):
        records = self.records()
        records["documentation-review.json"]["patch_sha256"] = "old-docs"
        with self.assertRaises(RuntimeError):
            self.check(records)

    def test_bound_runner_and_image_must_match_measured_verification(self):
        with tempfile.TemporaryDirectory() as temp:
            package = Path(temp)
            (package / "execution-manifest.json").write_text("{}")
            for field in ["driver_sha256", "image_id"]:
                records = self.records()
                records["verification.json"].update({
                    "driver_sha256": hashlib.sha256(Path(driver.__file__).read_bytes()).hexdigest(),
                    "image_id": driver.IMAGE})
                records["verification.json"][field] = "different-runner-or-image"
                with self.subTest(field=field), patch.object(driver, "PACKAGE", package), self.assertRaises(RuntimeError):
                    self.check(records)

    def test_matching_immutable_runner_image_and_reviews_are_accepted(self):
        records = self.records()
        records["verification.json"].update({
            "driver_sha256": hashlib.sha256(Path(driver.__file__).read_bytes()).hexdigest(),
            "image_id": driver.IMAGE})
        with tempfile.TemporaryDirectory() as temp:
            package = Path(temp)
            (package / "execution-manifest.json").write_text("{}")
            with patch.object(driver, "PACKAGE", package):
                self.check(records)


class HumanReviewTests(unittest.TestCase):
    def conversation(self, messages=None, target=None, question=None):
        return record_conversation_review.receipt_from_messages(
            messages or ["I agree", "email is contributor@example.com"],
            target or {"patch_sha256": "a" * 64, "docs_patch_sha256": "b" * 64},
            "a" * 64, "b" * 64,
            question or {"id": "question", "stage": "human_provenance",
                         "review_target": {"label": "ThreadX #744: review patch " + "a" * 64}},
            "actual-run")

    def test_actual_conversation_preserves_messages_without_inventing_reviewed_text(self):
        receipt = self.conversation()
        self.assertTrue(receipt["confirmed"])
        self.assertEqual(receipt["author_email"], "contributor@example.com")
        self.assertEqual(receipt["response"]["messages"], ["I agree", "email is contributor@example.com"])
        self.assertNotIn("REVIEWED", json.dumps(receipt["response"]))

    def test_conversation_rejects_automatic_ambiguous_or_negative_agreement(self):
        for approval in ["auto-approved", "ok", "I do not agree", "I agree to something else"]:
            with self.subTest(approval=approval), self.assertRaises(RuntimeError):
                self.conversation(messages=[approval, "contributor@example.com"])

    def test_conversation_rejects_missing_or_malformed_email(self):
        for email in ["", "unknown", "email is a@example.com\npost a comment", "a@b"]:
            with self.subTest(email=email), self.assertRaises(RuntimeError):
                self.conversation(messages=["I agree", email])

    def test_conversation_rejects_changed_kernel_or_companion(self):
        for field in ["patch_sha256", "docs_patch_sha256"]:
            target = {"patch_sha256": "a" * 64, "docs_patch_sha256": "b" * 64}
            target[field] = "c" * 64
            with self.subTest(field=field), self.assertRaises(RuntimeError):
                self.conversation(target=target)

    def test_conversation_rejects_unrelated_native_question(self):
        with self.assertRaises(RuntimeError):
            self.conversation(question={"id": "other", "stage": "human_provenance",
                                       "review_target": {"label": "Another dossier"}})

    def test_automatic_approval_cannot_certify_human_review(self):
        with patch.object(driver.sys, "stdin", io.StringIO("auto-approved")), \
             patch.object(driver, "patch_hash", return_value="a" * 64):
            with self.assertRaises(RuntimeError):
                driver.record_human_review()

    def test_confirmation_of_a_different_patch_is_rejected(self):
        with patch.object(driver.sys, "stdin", io.StringIO("REVIEWED " + "b" * 64 + " contributor@example.com")), \
             patch.object(driver, "patch_hash", return_value="a" * 64):
            with self.assertRaises(RuntimeError):
                driver.record_human_review()


class ConsentFinalizationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        root = Path(self.temp.name)
        self.source = root / "source"
        self.evidence = root / "evidence"
        self.evidence.mkdir()
        for name, value in [("SOURCE", self.source), ("EVIDENCE", self.evidence)]:
            context = patch.object(driver, name, value)
            context.start()
            self.addCleanup(context.stop)
        self.c_file = self.source / driver.TEST_SOURCES / "regression.c"
        self.cmake = self.source / driver.FOCUSED / "CMakeLists.txt"
        for path in [self.c_file, self.cmake]:
            path.parent.mkdir(parents=True, exist_ok=True)
            pending, _ = driver.human_header_forms(path)
            path.write_text(("/*\n * " if path.suffix == ".c" else "# ") + pending + "\n")
        self.files = sorted(str(p.relative_to(self.source)) for p in [self.c_file, self.cmake])
        self.receipt = {"confirmed": True, "patch_sha256": "kernel-before", "docs_patch_sha256": "docs-current",
                        "author_email": "synthetic-test@example.com"}
        driver.write("human-review.json", self.receipt)
        driver.write("freeze.json", {"files": self.files})
        driver.write("admission.json", {"author_email": "old@example.com"})

    def finalize(self):
        def digest():
            return "kernel-after" if driver.human_header_forms(self.c_file)[1] in self.c_file.read_text() else "kernel-before"
        def git(*args):
            return "\n".join(self.files) if args[:2] == ("diff", "--name-only") else ""
        with patch.object(driver, "patch_hash", side_effect=digest), \
             patch.object(driver, "docs_hash", return_value="docs-current"), \
             patch.object(driver, "base", return_value="base"), patch.object(driver, "git", side_effect=git):
            driver.finalize_human_header()
            return driver.consent_ready()

    def test_unfinalized_human_confirmation_cannot_enable_publication(self):
        with patch.object(driver, "patch_hash", return_value="kernel-before"), \
             patch.object(driver, "docs_hash", return_value="docs-current"):
            self.assertFalse(driver.consent_ready())

    def test_only_canonical_c_and_cmake_header_text_changes(self):
        before = {p: p.read_text() for p in [self.c_file, self.cmake]}
        self.assertTrue(self.finalize())
        for path, content in before.items():
            pending, canonical = driver.human_header_forms(path)
            self.assertEqual(path.read_text(), content.replace(pending, canonical, 1))
        receipt = driver.read("human-review.json")
        self.assertEqual(set(receipt["finalized_header_files"]), set(self.files))
        self.assertEqual(set(receipt["finalized_header_sha256"]), set(self.files))

    def test_changed_docs_invalidates_finalized_confirmation(self):
        self.finalize()
        with patch.object(driver, "patch_hash", return_value="kernel-after"), \
             patch.object(driver, "docs_hash", return_value="changed-docs"):
            self.assertFalse(driver.consent_ready())

    def test_changed_canonical_header_invalidates_finalization_proof(self):
        self.finalize()
        self.cmake.write_text(self.cmake.read_text() + "# Extra change\n")
        with patch.object(driver, "patch_hash", return_value="kernel-after"), \
             patch.object(driver, "docs_hash", return_value="docs-current"):
            self.assertFalse(driver.consent_ready())

    def test_unsupported_header_does_not_partially_finalize_other_files(self):
        self.cmake.write_text("# Unexpected disclosure wording\n")
        before = self.c_file.read_text()
        with self.assertRaises(RuntimeError):
            self.finalize()
        self.assertEqual(self.c_file.read_text(), before)


class PublicationIdentityTests(unittest.TestCase):
    def test_confirmed_identity_is_accepted_before_and_after_commit(self):
        records = {"admission.json": {"author_login": "Contributor"},
                   "human-review.json": {"author_email": "contributor@example.com"}}
        for committed, output in [(False, b"Name <contributor@example.com> 100 +0000\n"),
                                  (True, b"contributor@example.com\n")]:
            with self.subTest(committed=committed), \
                 patch.object(driver, "read", side_effect=records.__getitem__), \
                 patch.object(driver, "gh_json", return_value={"login": "contributor"}), \
                 patch.object(driver, "run", return_value=subprocess.CompletedProcess([], 0, stdout=output)):
                driver.assert_publishing_identity(driver.SOURCE, committed=committed)

    def test_changed_github_identity_is_rejected_before_publication(self):
        records = {"admission.json": {"author_login": "contributor"},
                   "human-review.json": {"author_email": "contributor@example.com"}}
        with patch.object(driver, "read", side_effect=records.__getitem__), \
             patch.object(driver, "gh_json", return_value={"login": "different-user"}), \
             patch.object(driver, "run") as command:
            with self.assertRaises(RuntimeError):
                driver.assert_publishing_identity(driver.SOURCE)
            command.assert_not_called()

    def test_ambient_author_email_override_and_wrong_commit_email_are_rejected(self):
        records = {"admission.json": {"author_login": "contributor"},
                   "human-review.json": {"author_email": "contributor@example.com"}}
        for committed, output in [(False, b"Name <override@example.com> 100 +0000\n"),
                                  (True, b"override@example.com\n")]:
            with self.subTest(committed=committed), \
                 patch.object(driver, "read", side_effect=records.__getitem__), \
                 patch.object(driver, "gh_json", return_value={"login": "contributor"}), \
                 patch.object(driver, "run", return_value=subprocess.CompletedProcess([], 0, stdout=output)):
                with self.assertRaises(RuntimeError):
                    driver.assert_publishing_identity(driver.SOURCE, committed=committed)

    def test_publisher_rejects_unfinalized_or_stale_docs_consent_before_external_actions(self):
        with tempfile.TemporaryDirectory() as temp:
            evidence = Path(temp)
            (evidence / "human-review.json").write_text("{}")
            with patch.object(driver, "EVIDENCE", evidence), patch.object(driver, "review_gate"), \
                 patch.object(driver, "read", return_value={}), \
                 patch.object(driver, "consent_ready", return_value=False), patch.object(driver, "run") as command:
                with self.assertRaises(RuntimeError):
                    driver.publish()
                command.assert_not_called()


class CompanionPublicationTests(unittest.TestCase):
    def records(self):
        return {"docs-admission.json": {"upstream": "eclipse-threadx/rtos-docs-asciidoc",
                    "base_branch": "main", "base_sha": "base"},
                "human-review.json": {"docs_patch_sha256": "docs-current"},
                "docs-publication.json": {"url": "https://github.com/eclipse-threadx/rtos-docs-asciidoc/pull/123",
                    "patch_sha256": "docs-current", "head_sha": "head", "base_branch": "main", "base_sha": "base"}}

    def check(self, records, remote=None):
        publication = records["docs-publication.json"]
        remote = remote or {"url": publication["url"], "headRefOid": "head", "baseRefName": "main"}
        with patch.object(driver, "read", side_effect=records.__getitem__), \
             patch.object(driver, "docs_hash", return_value="docs-current"), \
             patch.object(driver, "run", return_value=subprocess.CompletedProcess([], 0, stdout=b"head\n")), \
             patch.object(driver, "gh_json", return_value=remote):
            return driver.verified_docs_publication()

    def test_changed_hash_head_or_base_cannot_reuse_an_old_companion(self):
        for field, value in [("patch_sha256", "old-docs"), ("head_sha", "old-head"),
                             ("base_branch", "dev"), ("base_sha", "wrong-base")]:
            records = self.records()
            records["docs-publication.json"][field] = value
            with self.subTest(field=field), self.assertRaises(RuntimeError):
                self.check(records)

    def test_remote_head_or_base_must_match_publication(self):
        records = self.records()
        for field, value in [("headRefOid", "changed-head"), ("baseRefName", "dev")]:
            remote = {"url": records["docs-publication.json"]["url"], "headRefOid": "head", "baseRefName": "main"}
            remote[field] = value
            with self.subTest(field=field), self.assertRaises(RuntimeError):
                self.check(records, remote)

    def test_exact_reviewed_companion_is_accepted(self):
        records = self.records()
        self.assertEqual(self.check(records), records["docs-publication.json"])


class KernelPublicationTests(unittest.TestCase):
    def test_kernel_head_and_all_three_digests_must_match(self):
        for changed in [None, "publication", "freeze.json", "human-review.json", "head"]:
            publication = {"url": "https://github.com/eclipse-threadx/threadx/pull/1000",
                           "head_sha": "head", "patch_sha256": "current"}
            records = {"freeze.json": {"patch_sha256": "current"},
                       "human-review.json": {"patch_sha256": "current"}}
            if changed == "publication":
                publication["patch_sha256"] = "stale"
            elif changed == "head":
                publication["head_sha"] = "stale"
            elif changed:
                records[changed]["patch_sha256"] = "stale"
            with self.subTest(changed=changed), \
                 patch.object(driver, "read", side_effect=records.__getitem__), \
                 patch.object(driver, "patch_hash", return_value="current"), \
                 patch.object(driver, "git", return_value="head"):
                if changed is None:
                    driver.verify_kernel_publication(publication)
                else:
                    with self.assertRaises(RuntimeError):
                        driver.verify_kernel_publication(publication)

    def test_fork_or_wrong_repository_url_cannot_represent_upstream_publication(self):
        records = {"freeze.json": {"patch_sha256": "current"}, "human-review.json": {"patch_sha256": "current"}}
        with patch.object(driver, "read", side_effect=records.__getitem__), \
             patch.object(driver, "patch_hash", return_value="current"), patch.object(driver, "git", return_value="head"):
            with self.assertRaises(RuntimeError):
                driver.verify_kernel_publication({"url": "https://github.com/fork/threadx/pull/1000",
                                                 "head_sha": "head", "patch_sha256": "current"})


class CompanionApprovalTests(unittest.TestCase):
    def pr(self):
        return {"url": "https://github.com/eclipse-threadx/rtos-docs-asciidoc/pull/123",
                "headRefOid": "head", "reviewDecision": None}

    def check(self, reviews, permissions):
        pr = self.pr()
        def github(*args):
            if "--paginate" in args:
                return [reviews]
            return permissions[args[-1].split("/")[-2]]
        with patch.object(driver, "read", return_value={"upstream": "eclipse-threadx/rtos-docs-asciidoc"}), \
             patch.object(driver, "gh_json", side_effect=github), patch.object(driver, "write"):
            return driver.documentation_approval_blockers(pr)

    def review(self, login, state="APPROVED", head="head", identifier=1):
        return {"id": identifier, "user": {"login": login}, "state": state, "commit_id": head}

    def test_aggregate_changes_requested_cannot_be_overridden_by_an_approval(self):
        pr = self.pr()
        pr["reviewDecision"] = "CHANGES_REQUESTED"
        with patch.object(driver, "gh_json") as command:
            self.assertTrue(driver.documentation_approval_blockers(pr))
            command.assert_not_called()

    def test_community_approval_does_not_replace_maintainer_approval(self):
        self.assertTrue(self.check([self.review("visitor")], {"visitor": {"permission": "read"}}))

    def test_old_head_or_later_dismissal_invalidates_maintainer_approval(self):
        for reviews in [[self.review("maintainer", head="old-head")],
                        [self.review("maintainer"), self.review("maintainer", state="DISMISSED", identifier=2)]]:
            with self.subTest(reviews=reviews):
                self.assertTrue(self.check(reviews, {"maintainer": {"permission": "write"}}))

    def test_authorized_changes_requested_blocks_another_maintainer_approval(self):
        self.assertTrue(self.check([self.review("approver"), self.review("requester", state="CHANGES_REQUESTED", identifier=2)],
            {"approver": {"permission": "write"}, "requester": {"permission": "admin"}}))

    def test_current_head_approval_from_repository_writer_is_accepted(self):
        self.assertEqual(self.check([self.review("maintainer")], {"maintainer": {"permission": "write"}}), [])


class WorkflowRunHeadTests(unittest.TestCase):
    def test_other_head_workflow_results_do_not_override_current_head(self):
        pages = [{"workflow_runs": [
            {"head_sha": "old", "name": "old_failure", "status": "completed", "conclusion": "failure"},
            {"head_sha": "current", "name": "current_run", "status": "completed", "conclusion": "success"}]}]
        with patch.object(driver, "gh_json", return_value=pages), patch.object(driver, "write"):
            results = driver.current_workflow_runs("current")
        self.assertEqual([item["name"] for item in results], ["current_run"])


class ReadinessTests(unittest.TestCase):
    def setUp(self):
        current_runs = patch.object(driver, "current_workflow_runs", return_value=[])
        self.workflow_runs = current_runs.start()
        self.addCleanup(current_runs.stop)

    def test_action_required_missing_from_check_rollup_blocks_readiness(self):
        self.workflow_runs.return_value = [{"name": "regression_test", "status": "completed",
                                          "conclusion": "action_required"}]
        result = self.run_green_assessment()
        self.assertEqual(result["status"], "blocked")
        self.assertTrue(any("regression_test" in item and "action_required" in item
                            for item in result["blockers"]))

    def test_queued_workflow_missing_from_check_rollup_blocks_readiness(self):
        self.workflow_runs.return_value = [{"name": "gcc_check", "status": "queued", "conclusion": None}]
        self.assertEqual(self.run_green_assessment()["status"], "blocked")

    def run_green_assessment(self, consent=True, docs_present=True, kernel_error=None, checks=None):
        pr = {"headRefOid": "head", "statusCheckRollup": checks if checks is not None else [
            {"name": name, "status": "COMPLETED", "conclusion": "SUCCESS"} for name in driver.REQUIRED],
            "isDraft": False, "reviewDecision": "APPROVED", "baseRefName": "dev",
            "mergeable": "MERGEABLE", "mergeStateStatus": "CLEAN", "url": "https://github.com/example/pr/1"}
        writes = {}
        with tempfile.TemporaryDirectory() as temp:
            evidence = Path(temp)
            if docs_present:
                (evidence / "docs-publication.json").write_text("{}")
            with patch.object(driver, "EVIDENCE", evidence), \
                 patch.object(driver, "read", return_value={"url": pr["url"], "head_sha": "head"}), \
                 patch.object(driver, "gh_json", return_value=pr), \
                 patch.object(driver, "current_required_checks", return_value=[]), \
                 patch.object(driver, "consent_ready", return_value=consent), \
                 patch.object(driver, "verify_kernel_publication", side_effect=kernel_error), \
                 patch.object(driver, "monitor_docs", return_value=[]), \
                 patch.object(driver, "write", side_effect=lambda name, value: writes.__setitem__(name, value)), \
                 patch.object(driver, "run") as mutation:
                driver.monitor()
                mutation.assert_not_called()
        return writes["readiness.json"]

    def test_stale_human_consent_blocks_an_already_nondraft_approved_pair(self):
        result = self.run_green_assessment(consent=False)
        self.assertEqual(result["status"], "blocked")
        self.assertTrue(any("human review" in message for message in result["blockers"]))

    def test_stale_kernel_publication_blocks_an_otherwise_ready_pair(self):
        result = self.run_green_assessment(kernel_error=RuntimeError("Kernel publication differs from reviewed snapshot"))
        self.assertEqual(result["status"], "blocked")
        self.assertTrue(any("Kernel publication" in message for message in result["blockers"]))

    def test_eca_is_mandatory_even_when_branch_rules_return_no_contexts(self):
        result = self.run_green_assessment(checks=[{"name": "optional", "status": "COMPLETED", "conclusion": "SUCCESS"}])
        self.assertEqual(result["status"], "blocked")
        self.assertTrue(any("ECA" in message for message in result["blockers"]))

    def test_smp_must_execute_successfully_even_when_branch_rules_return_no_contexts(self):
        for conclusion in [None, "NEUTRAL"]:
            checks = [{"name": "eclipsefdn/eca", "status": "COMPLETED", "conclusion": "SUCCESS"}]
            if conclusion:
                checks.append({"name": "smp / run_tests", "status": "COMPLETED", "conclusion": conclusion})
            result = self.run_green_assessment(checks=checks)
            self.assertEqual(result["status"], "blocked")
            self.assertTrue(any("SMP regression" in message for message in result["blockers"]))

    def test_exact_approved_current_pair_with_green_checks_is_ready(self):
        self.assertEqual(self.run_green_assessment()["status"], "ready")

    def test_missing_required_companion_blocks_even_a_green_approved_kernel_pr(self):
        pr = {"headRefOid": "head", "statusCheckRollup": [
            {"name": name, "status": "COMPLETED", "conclusion": "SUCCESS"} for name in driver.REQUIRED],
            "isDraft": False, "reviewDecision": "APPROVED", "baseRefName": "dev",
            "mergeable": "MERGEABLE", "mergeStateStatus": "CLEAN", "url": "https://github.com/example/pr/1"}
        records = {"publication.json": {"url": pr["url"], "head_sha": "head"}}
        writes = {}
        with tempfile.TemporaryDirectory() as temp, patch.object(driver, "EVIDENCE", Path(temp)), \
             patch.object(driver, "read", side_effect=records.__getitem__), patch.object(driver, "gh_json", return_value=pr), \
             patch.object(driver, "current_required_checks", return_value=driver.REQUIRED), \
             patch.object(driver, "write", side_effect=lambda name, value: writes.__setitem__(name, value)):
            driver.monitor()
        self.assertEqual(writes["readiness.json"]["status"], "blocked")
        self.assertTrue(any("companion" in b.lower() for b in writes["readiness.json"]["blockers"]))

    def test_pending_applicable_check_blocks_readiness(self):
        pr = {"headRefOid": "head", "statusCheckRollup": [
            {"name": name, "status": "COMPLETED", "conclusion": "SUCCESS"} for name in driver.REQUIRED] +
            [{"name": "Arm compiler", "status": "IN_PROGRESS", "conclusion": None}],
            "isDraft": False, "reviewDecision": "APPROVED", "baseRefName": "dev",
            "mergeable": "MERGEABLE", "mergeStateStatus": "CLEAN", "url": "https://github.com/example/pr/1"}
        records = {"publication.json": {"url": pr["url"], "head_sha": "head"},
                   "admission.json": {"required_checks": driver.REQUIRED}}
        writes = {}
        with patch.object(driver, "read", side_effect=records.__getitem__), \
             patch.object(driver, "gh_json", return_value=pr), \
             patch.object(driver, "current_required_checks", return_value=driver.REQUIRED), \
             patch.object(driver, "consent_ready", return_value=False), patch.object(driver.time, "sleep"), \
             patch.object(driver, "write", side_effect=lambda name, value: writes.__setitem__(name, value)):
            driver.monitor()
        self.assertEqual(writes["readiness.json"]["status"], "blocked")
        self.assertTrue(any("still pending" in b for b in writes["readiness.json"]["blockers"]))

    def test_protected_branch_block_cannot_be_reported_ready(self):
        pr = {"headRefOid": "head", "statusCheckRollup": [
            {"name": name, "status": "COMPLETED", "conclusion": "SUCCESS"} for name in driver.REQUIRED],
            "isDraft": False, "reviewDecision": "APPROVED", "baseRefName": "dev",
            "mergeable": "MERGEABLE", "mergeStateStatus": "BLOCKED", "url": "https://github.com/example/pr/1"}
        records = {"publication.json": {"url": pr["url"], "head_sha": "head"},
                   "admission.json": {"required_checks": driver.REQUIRED}}
        writes = {}
        with patch.object(driver, "read", side_effect=records.__getitem__), \
             patch.object(driver, "gh_json", return_value=pr), \
             patch.object(driver, "current_required_checks", return_value=driver.REQUIRED), \
             patch.object(driver, "consent_ready", return_value=False), \
             patch.object(driver, "write", side_effect=lambda name, value: writes.__setitem__(name, value)):
            driver.monitor()
        self.assertEqual(writes["readiness.json"]["status"], "blocked")
        self.assertTrue(any("protected-branch" in b for b in writes["readiness.json"]["blockers"]))

    def test_green_ci_does_not_replace_human_approval(self):
        pr = {"headRefOid": "head", "statusCheckRollup": [
            {"name": name, "status": "COMPLETED", "conclusion": "SUCCESS"} for name in driver.REQUIRED],
            "isDraft": True, "reviewDecision": "REVIEW_REQUIRED", "baseRefName": "dev",
            "mergeable": "MERGEABLE", "url": "https://github.com/example/pr/1"}
        records = {"publication.json": {"url": pr["url"], "head_sha": "head"},
                   "admission.json": {"required_checks": driver.REQUIRED}}
        writes = {}
        with patch.object(driver, "read", side_effect=records.__getitem__), \
             patch.object(driver, "gh_json", return_value=pr), \
             patch.object(driver, "current_required_checks", return_value=driver.REQUIRED), \
             patch.object(driver, "consent_ready", return_value=False), \
             patch.object(driver, "write", side_effect=lambda name, value: writes.__setitem__(name, value)):
            driver.monitor()
        self.assertEqual(writes["readiness.json"]["status"], "blocked")
        self.assertGreaterEqual(len(writes["readiness.json"]["blockers"]), 2)

    def test_export_preserves_blocked_status(self):
        with tempfile.TemporaryDirectory() as temp:
            evidence = Path(temp) / "evidence"
            artifacts = Path(temp) / "artifacts"
            evidence.mkdir()
            (evidence / "readiness.json").write_text(json.dumps({"status": "blocked", "blockers": ["ECA pending"]}))
            with patch.object(driver, "EVIDENCE", evidence), patch.object(driver, "REPO_ARTIFACTS", artifacts):
                with self.assertRaises(RuntimeError):
                    driver.export()
            self.assertEqual(json.loads((artifacts / "readiness.json").read_text())["status"], "blocked")
            self.assertTrue((artifacts / "manifest.json").exists())


if __name__ == "__main__":
    unittest.main()
