# SPDX-License-Identifier: Apache-2.0
# Generated layout: compiles upstream inc_diagnostics sources in place with Cargo.
[package]
name = "uds"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "../../../../upstream/inc_diagnostics-pr6/score/mw/diag/api/uds.rs"

[dependencies]
common = { path = "../common" }
