' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!startsub Logger
package mw::log <<frame>> {
    class Logger {
    }

}
!endsub

!startsub ByteVector
package mw::diag <<frame>> {
        ByteVector : score::cpp::pmr::vector<std::uint8_t>
}
!endsub

!startsub MemoryResource
class score::cpp::pmr::memory_resource{
    + score::cpp::pmr::get_default_resource() : score::cpp::pmr::memory_resource*
}
!endsub

!startsub InternalConfigProviderSkeleton
package portinterfaces::internalconfigprovider::skeleton <<frame>> {
    class InternalConfigProviderSkeleton <<generated>> {
        This class is generated based on franca definition.
    }
}
!endsub

!startsub DiagnosticJobCollection
package mw::diag <<frame>> {
    class DiagnosticJobCollection {
    }
}
!endsub

!startsub ProvidedServiceContainer
package mw::service <<frame>> {
    class ProvidedServiceContainer {
    }
}
!endsub

!startsub ConfigCalibrationSkeleton
package ara <<frame>> {
    class ConfigCalibrationSkeleton <<generated>> {
        This class is generated based on franca definition.
    }
}
!endsub

!startsub ProvidedServiceBuilder
package mw::service <<frame>> {
    class ProvidedServiceBuilder {
    }
}
!endsub

@enduml
