# SPDX-License-Identifier: Apache-2.0
# Generated layout: compiles upstream inc_diagnostics sources in place with Cargo.
[package]
name = "simple_operation"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "../../../../upstream/inc_diagnostics-pr6/score/mw/diag/api/simple_operation.rs"

[dependencies]
common = { path = "../common" }
operation = { path = "../operation" }
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
