#!/usr/bin/env python3
# Copyright (c) 2026 Eclipse SDV Hackathon Team
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).
# The AI-generated portions may be considered public domain (CC0-1.0).
# Human provenance review and verification are pending.
#
# SPDX-License-Identifier: Apache-2.0 AND CC0-1.0

"""Deterministic contribution gates; agent assertions never replace measurements."""
from __future__ import annotations

import hashlib
import html
import json
import os
import re
from pathlib import Path
import shutil
import subprocess
import sys
import time
import urllib.request
import xml.etree.ElementTree as ET

PACKAGE = Path(__file__).resolve().parent
REPO_ARTIFACTS = Path("/home/jefferson/Thinking_CAPs/contributions/threadx-744/artifacts")
ROOT = Path("/media/jefferson/11c42dee-73a3-4c2b-ab42-a0440011d9e0/threadx-contributions/744")
SOURCE = ROOT / "source"
DOCS = ROOT / "docs-source"
EVIDENCE = ROOT / "evidence"
IMAGE = "sha256:a8a3d92ee0ba622304a79ce1dcc51aba1ad1d0ac52767c71b7c1e158520275cc"
UPSTREAM = "eclipse-threadx/threadx"
MODEL = "gpt-6.1-sol"
EFFORT = "high"
FOCUSED = "test/tx/cmake/thread_stack_alignment"
TEST_SOURCES = "test/tx/thread_stack_alignment"
REQUIRED = ["eclipsefdn/eca", "tx / run_tests", "smp / run_tests", "freertos / run_tests", "riscv / run_tests"]


def write(name, value):
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    p = EVIDENCE / name
    p.write_text(json.dumps(value, indent=2) + "\n")
    return value


def read(name):
    return json.loads((EVIDENCE / name).read_text())


def run(argv, cwd=SOURCE, timeout=120, check=True, log=None, env=None):
    started = time.time()
    if log:
        p = EVIDENCE / log
        p.parent.mkdir(parents=True, exist_ok=True)
        with p.open("w") as stream:
            stream.write("COMMAND " + json.dumps(argv) + "\n")
            stream.flush()
            result = subprocess.run(argv, cwd=cwd, env=env, stdout=stream,
                                    stderr=subprocess.STDOUT, timeout=timeout)
        record = {"argv": argv, "cwd": str(cwd), "exit_code": result.returncode,
                  "seconds": round(time.time() - started, 2), "log": log}
        write(log + ".json", record)
        if check and result.returncode:
            raise RuntimeError(f"Command failed ({result.returncode}); see {p}")
        return record
    result = subprocess.run(argv, cwd=cwd, env=env, capture_output=True, timeout=timeout)
    if check and result.returncode:
        raise RuntimeError(f"Command failed: {argv[:3]}: {result.stderr.decode(errors='replace')[-1200:]}")
    return result


def git(*args):
    return run(["git", *args]).stdout.decode().strip()


def gh_json(*args):
    return json.loads(run(["gh", *args]).stdout)


def base():
    return read("admission.json")["base_sha"]


def patch_bytes():
    return run(["git", "diff", "--binary", base(), "--"]).stdout


def patch_hash():
    return hashlib.sha256(patch_bytes()).hexdigest()


def docs_hash():
    admission = read("docs-admission.json")
    data = run(["git", "diff", "--binary", admission["base_sha"], "--"], cwd=DOCS).stdout
    return hashlib.sha256(data).hexdigest()


def check_license_headers(phase="preparation"):
    """Execute the scoped license audit; agents cannot waive missing headers."""
    report = "license-headers-final.json" if phase == "publication" else "license-headers.json"
    return run([sys.executable, str(PACKAGE / "license_audit.py"),
        "--source", str(SOURCE), "--docs", str(DOCS),
        "--base", base(), "--docs-base", read("docs-admission.json")["base_sha"],
        "--workflow", str(REPO_ARTIFACTS.parent / "workflow"),
        "--artifacts", str(REPO_ARTIFACTS), "--phase", phase,
        "--output", str(EVIDENCE / report)], cwd=PACKAGE,
        log="verification/license-headers" + ("-final" if phase == "publication" else "") + ".log")


def smp_host_cpus():
    cpus = []
    seen = set()
    for cpu in sorted(os.sched_getaffinity(0)):
        topology = Path(f"/sys/devices/system/cpu/cpu{cpu}/topology")
        core = ((topology / "physical_package_id").read_text().strip(),
                (topology / "core_id").read_text().strip())
        if core not in seen:
            seen.add(core)
            cpus.append(cpu)
        if len(cpus) == 4:
            break
    return cpus


def docker(args, directory="/work", timeout=1200, log="command.log", check=True, src=SOURCE, smp=False):
    # Bound Linux host concurrency for the four-core SMP simulator. A recorded
    # first failure and diagnostic comparisons motivate this environment setting.
    cpus = smp_host_cpus()
    affinity = ["--cpuset-cpus", ",".join(map(str, cpus))] if smp or "scripts/test_smp.sh" in args else []
    return run(["docker", "run", "--rm", "--network", "none", *affinity, "--user",
                f"{os.getuid()}:{os.getgid()}", "--cap-add", "SYS_NICE",
                "--ulimit", "rtprio=3:3", "-v", f"{src}:/work",
                "-v", f"{EVIDENCE}:/evidence", "-w", directory, IMAGE, *args],
               timeout=timeout, log=log, check=check)


def admit():
    if run(["findmnt", "-rn", "-S", "/dev/loop4", "-o", "TARGET"]).stdout.decode().strip() != str(ROOT.parents[1]):
        raise RuntimeError("Requested loop4 filesystem is not mounted at the configured storage root")
    if git("status", "--porcelain"):
        raise RuntimeError("Admission requires an isolated clean upstream checkout")
    issue = gh_json("issue", "view", "744", "--repo", UPSTREAM, "--json", "number,title,body,comments,state,assignees,url")
    if issue["state"] != "OPEN":
        raise RuntimeError("Issue #744 is no longer open; re-assess before implementation")
    git("fetch", "origin", "dev")
    sha = git("rev-parse", "HEAD")
    if sha != git("rev-parse", "origin/dev"):
        raise RuntimeError("Admission checkout must match the freshly fetched dev branch")
    contributor = gh_json("api", "user")
    write("issue.json", issue)
    rules = gh_json("api", f"repos/{UPSTREAM}/rules/branches/dev")
    write("upstream-rules.json", rules)
    required = [s["context"] for r in rules if r["type"] == "required_status_checks"
                for s in r["parameters"]["required_status_checks"]]
    dependencies = {}
    for number in [741, 742, 532]:
        kind = "pulls" if number == 742 else "issues"
        item = gh_json("api", f"repos/{UPSTREAM}/{kind}/{number}")
        dependencies[str(number)] = {k: item.get(k) for k in ["number", "state", "title", "html_url", "merged_at", "merge_commit_sha"]}
    write("dependencies.json", dependencies)
    guide = (SOURCE / "CONTRIBUTING.md").read_text()
    (EVIDENCE / "CONTRIBUTING.md").write_text(guide)
    (EVIDENCE / "PR-template.md").write_text((SOURCE / ".github/PULL_REQUEST_TEMPLATE.md").read_text())
    write("agent-settings.json", {"backend": "Codex CLI", "model": MODEL,
          "reasoning_effort": EFFORT, "fallbacks": [],
          "probe": "model-probe.jsonl", "human_review": "pending"})
    write("admission.json", {"base_sha": sha, "branch": git("branch", "--show-current"),
          "base_branch": "dev", "upstream": UPSTREAM,
          "author_login": contributor["login"], "author_name": contributor["name"],
          "author_email": git("config", "user.email"), "required_checks": required,
          "guide_sha256": hashlib.sha256(guide.encode()).hexdigest(),
          "coordination": "Issue is assigned; no issue comment sent by this workflow",
          "legal": "ECA must be confirmed by the external final-head check",
          "status": "admitted"})
    if not DOCS.exists():
        run(["git", "clone", "--branch", "main", "--single-branch",
             "https://github.com/eclipse-threadx/rtos-docs-asciidoc.git", str(DOCS)], timeout=300)
    if run(["git", "status", "--porcelain"], cwd=DOCS).stdout.strip():
        raise RuntimeError("Full admission requires a clean companion documentation checkout")
    run(["git", "fetch", "origin", "main"], cwd=DOCS)
    docs_sha = run(["git", "rev-parse", "HEAD"], cwd=DOCS).stdout.decode().strip()
    if docs_sha != run(["git", "rev-parse", "origin/main"], cwd=DOCS).stdout.decode().strip():
        raise RuntimeError("Companion checkout must match freshly fetched main")
    docs_branch = run(["git", "branch", "--show-current"], cwd=DOCS).stdout.decode().strip()
    if docs_branch == "main":
        docs_branch = "docs/744-stack-pointer-width"
        run(["git", "switch", "-c", docs_branch], cwd=DOCS)
    write("docs-admission.json", {"upstream": "eclipse-threadx/rtos-docs-asciidoc",
          "base_branch": "main", "base_sha": docs_sha, "branch": docs_branch,
          "reason": "Required companion for corrected behavior", "prior_context_pr": 79})
    print("Admitted", sha, "required checks:", required)


def agent(role):
    roles = ["planner", "implement", "technical-review", "process-review", "repair", "pr-writer", "documentation", "documentation-review"]
    if role not in roles:
        raise RuntimeError("Unknown agent role")
    counts_path = EVIDENCE / "agent-visits.json"
    counts = json.loads(counts_path.read_text()) if counts_path.exists() else {}
    counts[role] = counts.get(role, 0) + 1
    write("agent-visits.json", counts)
    number = counts[role]
    prompt = (PACKAGE / "prompts" / (role + ".md")).read_text()
    values = {"issue_number": "744", "source_dir": str(SOURCE), "evidence_dir": str(EVIDENCE),
              "artifacts_dir": str(REPO_ARTIFACTS), "docs_dir": str(DOCS)}
    for key, value in values.items():
        prompt = prompt.replace("{{ inputs." + key + " }}", value)
    readonly = role in ["technical-review", "process-review", "documentation-review"]
    if readonly:
        prompt += "\nYou run read-only. Return the review JSON as your final response; the driver will save it. Do not try to write review files.\n"
    if role in ["implement", "repair"]:
        prompt += f"\nDeterministic verification contract: add a standalone CMake/CTest regression under {FOCUSED}. It must configure directly with cmake -S {FOCUSED} -B /evidence/build/focused -G Ninja -DCMAKE_C_COMPILER=gcc-14. Compile and execute actual common/src/tx_thread_create.c with real Linux header widths on x86_64 and both TX_MISRA_ENABLE and TX_ENABLE_STACK_CHECKING; the port boundary may use recording stubs following native thread_transition tests. Avoid starting scheduler threads on the old invalid pointer: fail safely on concrete pointer/stack metadata assertions. Test every alignment offset and guard boundaries. Add it to upstream host CTest discovery so CI actually executes a native64 target despite parent -m32 flags. Keep normal native32 coverage. No production edits except common/src/tx_thread_create.c. New-file AI header must name Codex (gpt-6.1-sol), and honestly state that human provenance review is pending; never assert completed human review. Scope may include explicit MISRA deviation comment naming applicable rule. Read design at {PACKAGE / 'regression-design.md' if (PACKAGE / 'execution-manifest.json').exists() else PACKAGE.parent / 'regression-design.md'}.\n"
    logdir = EVIDENCE / "agents"
    logdir.mkdir(exist_ok=True)
    stem = f"{role}-{number}"
    final = logdir / (stem + ".txt")
    argv = ["codex", "exec", "--ignore-user-config", "--ephemeral", "--model", MODEL,
            "-c", 'model_reasoning_effort="high"', "-c", 'approval_policy="never"',
            "--sandbox", "read-only" if readonly else "workspace-write", "--cd", str(SOURCE),
            "--json", "-o", str(final)]
    if not readonly:
        argv += ["--add-dir", str(EVIDENCE)]
        if role == "documentation":
            argv += ["--add-dir", str(DOCS)]
    if readonly:
        schema = {"type": "object", "additionalProperties": False,
                  "required": ["patch_sha256", "verdict", "findings", "readiness_blockers"],
                  "properties": {"patch_sha256": {"type": "string"},
                    "verdict": {"type": "string", "enum": ["pass", "fail"]},
                    "findings": {"type": "array", "items": {"type": "object", "additionalProperties": False,
                      "required": ["severity", "message", "evidence"],
                      "properties": {k: {"type": "string"} for k in ["severity", "message", "evidence"]}}},
                    "readiness_blockers": {"type": "array", "items": {"type": "string"}}}}
        schema_path = logdir / (stem + ".schema.json")
        schema_path.write_text(json.dumps(schema))
        argv += ["--output-schema", str(schema_path)]
    argv.append("-")
    env = os.environ.copy()
    env["TMPDIR"] = str(EVIDENCE / "tmp")
    Path(env["TMPDIR"]).mkdir(exist_ok=True)
    before = (patch_hash(), docs_hash() if (EVIDENCE / "docs-admission.json").exists() else None) if readonly else None
    with (logdir / (stem + ".jsonl")).open("w") as out, (logdir / (stem + ".stderr")).open("w") as err:
        result = subprocess.run(argv, input=prompt, text=True, stdout=out, stderr=err,
                                env=env, timeout=1800)
    write("agents/" + stem + ".invocation.json", {"role": role, "argv": argv,
          "model": MODEL, "reasoning_effort": EFFORT, "exit_code": result.returncode,
          "driver_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
          "prompt_sha256": hashlib.sha256(prompt.encode()).hexdigest()})
    if result.returncode:
        raise RuntimeError(f"Codex {role} failed; inspect {stem} logs")
    if readonly:
        if before != (patch_hash(), docs_hash() if (EVIDENCE / "docs-admission.json").exists() else None):
            raise RuntimeError("Read-only reviewer changed the frozen source")
        write(role + ".json", json.loads(final.read_text()))
        if role == "documentation-review":
            refresh_docs_pr_text()
    print("Completed Codex role", role, "visit", number)


def retire_prepared_outputs(history):
    """Retain old drafts for audit, then remove them from the current snapshot."""
    names = ["pr-title.txt", "pr-body.md", "review-gate.json", "readiness.json",
             "human-review-request.md", "human-review-target.json", "review.html"]
    for root, destination in [(EVIDENCE, history),
                              (REPO_ARTIFACTS, history / "artifact-mirrors")]:
        for name in names:
            path = root / name
            if path.exists():
                destination.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, destination / name)
                path.unlink()
    REPO_ARTIFACTS.mkdir(parents=True, exist_ok=True)
    (REPO_ARTIFACTS / "review.html").write_text(
        "<!doctype html><meta charset=utf-8><title>ThreadX review pending</title>"
        "<h1>Previous review dossier superseded</h1>"
        "<p>Fresh verification, independent reviews and PR text are pending. "
        "Do not approve the previous review request.</p>\n")


def freeze():
    untracked = git("ls-files", "--others", "--exclude-standard").splitlines()
    for path in untracked:
        if not path.startswith((FOCUSED + "/", TEST_SOURCES + "/")):
            raise RuntimeError("Unexpected untracked source: " + path)
        git("add", "-N", "--", path)
    paths = git("diff", "--name-only", base()).splitlines()
    allowed = {"common/src/tx_thread_create.c", "test/tx/cmake/CMakeLists.txt"}
    if "common/src/tx_thread_create.c" not in paths:
        raise RuntimeError("Expected production fix is absent")
    if not (SOURCE / FOCUSED / "CMakeLists.txt").exists():
        raise RuntimeError("Expected native-width regression is absent")
    if any(p not in allowed and not p.startswith((FOCUSED + "/", TEST_SOURCES + "/")) for p in paths):
        raise RuntimeError("Patch escaped the reviewed #744 scope")
    git("diff", "--check", base())
    data = patch_bytes()
    # Preserve evidence before a repair replaces the current candidate records.
    history = EVIDENCE / "history" / ("orphaned-drafts-" + time.strftime("%Y-%m-%dT%H%M%SZ", time.gmtime()))
    if (EVIDENCE / "freeze.json").exists():
        previous = read("freeze.json")
        history = EVIDENCE / "history" / (previous["frozen_at"].replace(":", "") + "-" + previous["patch_sha256"][:12])
        history.mkdir(parents=True, exist_ok=True)
        for name in ["freeze.json", "contribution.patch", "verification.json",
                     "technical-review.json", "process-review.json", "last-error.json", "license-headers.json"]:
            if (EVIDENCE / name).exists():
                shutil.copy2(EVIDENCE / name, history / name)
        if (EVIDENCE / "verification").exists():
            shutil.copytree(EVIDENCE / "verification", history / "verification", dirs_exist_ok=True)
    # Even an identical patch may have different measured results on a new run.
    # Drafts must be rewritten after the new verification and reviews complete.
    retire_prepared_outputs(history)
    check_license_headers()
    (EVIDENCE / "contribution.patch").write_bytes(data)
    write("freeze.json", {"patch_sha256": hashlib.sha256(data).hexdigest(),
          "base_sha": base(), "head_sha": git("rev-parse", "HEAD"), "files": paths,
          "frozen_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())})
    print("Frozen", patch_hash())


def reproduce_smp_baseline_failure(reports, baseline):
    """Classify only an executed, matching failure in unchanged SMP inputs."""
    target = "threadx_smp_random_resume_suspend_exclusion_pt_test"
    configurations = set()
    failures = []
    for path in reports.glob("*.xml"):
        if path.name == "coverage-merged.xml":
            continue
        for case in ET.parse(path).getroot().findall("testcase"):
            if case.find("failure") is None:
                continue
            name = case.attrib.get("name", "")
            if name.split("::")[-1] != target or "ERROR #7" not in case.findtext("system-out", ""):
                raise RuntimeError("Local SMP failure is outside the diagnosed baseline timing assertion")
            configuration = name.split("::")[0]
            configurations.add(configuration)
            failures.append({"test": name, "report": str(path.relative_to(EVIDENCE)), "assertion": "ERROR #7"})
    if not failures:
        raise RuntimeError("Failed SMP command did not report the diagnosed assertion")
    inputs = ["common_smp", "ports_smp", "test/smp", "test/shared", "test/tx/regression", "cmake", "scripts"]
    if git("diff", base(), "--", *inputs):
        raise RuntimeError("Candidate changes SMP build inputs; baseline classification is invalid")
    if run(["git", "rev-parse", "HEAD"], cwd=baseline).stdout.decode().strip() != base():
        raise RuntimeError("Baseline SMP worktree does not match the admitted upstream commit")
    if run(["git", "diff", base(), "--", *inputs], cwd=baseline).stdout.strip():
        raise RuntimeError("Original SMP production, tests or build inputs have changed")
    proof = {"base_sha": base(), "patch_sha256": patch_hash(), "image_id": IMAGE,
             "host_cpus": smp_host_cpus(), "unchanged_inputs": inputs,
             "candidate_failures": failures, "baseline_runs": []}
    for configuration in sorted(configurations):
        build_dir = "/evidence/build/baseline-smp-" + configuration
        docker(["cmake", "-S", "test/smp/cmake", "-B", build_dir, "-G", "Ninja",
                "-DCMAKE_TOOLCHAIN_FILE=/work/cmake/linux.cmake", "-DCMAKE_C_COMPILER=gcc-14",
                "-DCMAKE_BUILD_TYPE=" + configuration, "-DTX_COVERAGE=ON", "-DBUILD_SHARED_LIBS=ON"],
                src=baseline, log=f"verification/baseline-smp-{configuration}-configure.log")
        docker(["cmake", "--build", build_dir, "--target", target, "--parallel", "4"],
                src=baseline, log=f"verification/baseline-smp-{configuration}-build.log")
        reproduced = False
        for attempt in range(1, 11):
            log = f"verification/baseline-smp-{configuration}-{attempt}.log"
            measured = docker([build_dir + "/regression/" + target], src=baseline,
                              log=log, check=False, smp=True, timeout=15)
            output = (EVIDENCE / log).read_text()
            proof["baseline_runs"].append({"configuration": configuration, **measured})
            write("smp-baseline-reproduction.json", proof)
            if measured["exit_code"]:
                if measured["exit_code"] != 1 or "ERROR #7" not in output:
                    raise RuntimeError("Baseline failed for a different reason; timing classification is invalid")
                reproduced = True
                break
        if not reproduced:
            raise RuntimeError("Candidate SMP failure was not reproduced on its unchanged baseline within ten runs")
    proof["status"] = "failed-on-candidate-and-unchanged-baseline"
    write("smp-baseline-reproduction.json", proof)
    return proof


def verify():
    frozen = read("freeze.json")
    if frozen["patch_sha256"] != patch_hash():
        raise RuntimeError("Verification input differs from frozen patch")
    result = {"status": "fail", "patch_sha256": patch_hash(), "checks": [], "limitations": []}
    result["driver_sha256"] = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    result["smp_host_cpus"] = smp_host_cpus()
    write("verification.json", result)
    # A new patch gets fresh counters, CTest XML and gcovr output, including repairs.
    for path in [EVIDENCE / "build", EVIDENCE / "verification"]:
        if path.exists():
            shutil.rmtree(path)
    suite_dirs = {"tx": "test/tx/cmake", "smp": "test/smp/cmake",
                  "freertos": "test/freertos/cmake"}
    for directory in suite_dirs.values():
        for name in ["build", "coverage_report", "test_reports"]:
            path = SOURCE / directory / name
            if path.exists():
                shutil.rmtree(path)
    measured = check_license_headers()
    result["checks"].append({"name": "license-headers", "status": "pass", **measured})
    docker(["gcc-14", "--version"], log="verification/toolchain.log")
    result["image_id"] = run(["docker", "image", "inspect", IMAGE, "--format", "{{.Id}}"], cwd=PACKAGE).stdout.decode().strip()
    baseline = ROOT / "baseline"
    if not baseline.exists():
        run(["git", "worktree", "add", "--detach", str(baseline), base()])
    for directory in [FOCUSED, TEST_SOURCES]:
        test_source = SOURCE / directory
        if not test_source.exists():
            continue
        test_baseline = baseline / directory
        if test_baseline.exists():
            shutil.rmtree(test_baseline)
        shutil.copytree(test_source, test_baseline, ignore=shutil.ignore_patterns("build*", "*.gcda", "*.gcno"))
    # Build both trees with the identical candidate regression. Only production differs.
    for name, tree in [("baseline", baseline), ("focused", SOURCE)]:
        build_dir = f"/evidence/build/{name}"
        docker(["cmake", "-S", FOCUSED, "-B", build_dir, "-G", "Ninja",
                "-DCMAKE_C_COMPILER=gcc-14", "-DCMAKE_BUILD_TYPE=Debug"],
               src=tree, log=f"verification/{name}-configure.log")
        docker(["cmake", "--build", build_dir, "--parallel", "4"],
               src=tree, log=f"verification/{name}-build.log")
        measured = docker(["ctest", "--test-dir", build_dir, "--output-on-failure",
                 "--no-tests=error", "--timeout", "30", "--output-junit", f"/evidence/verification/{name}.xml"],
                 src=tree, log=f"verification/{name}-test.log", check=False)
        report = ET.parse(EVIDENCE / "verification" / (name + ".xml")).getroot()
        if not report.findall("testcase"):
            raise RuntimeError("Focused regression did not execute any test")
        if name == "baseline" and measured["exit_code"] == 0:
            raise RuntimeError("Regression also passes on old production code")
        if name == "baseline" and not any(t.find("failure") is not None for t in report.findall("testcase")):
            raise RuntimeError("Baseline did not record a behavioral assertion failure")
        if name == "focused" and measured["exit_code"] != 0:
            raise RuntimeError("Patched behavioral regression failed")
        result["checks"].append({"name": name, "status": "expected-failure" if name == "baseline" else "pass", **measured})
        write("verification.json", result)
    # Serialize suites and gcovr. Never hide a first failure with until-pass retries.
    failures = []
    baseline_smp_failure = None
    for suite, directory in suite_dirs.items():
        if suite == "freertos":
            # GCC 14 rejects the baseline layer's const-name mismatch in the
            # default profile. Exercise its supported constant-name API profile;
            # the stock profile is still required in upstream PR CI.
            profile = "-DCMAKE_C_FLAGS_DEFAULT_BUILD=-DTX_ENABLE_CONST_NAMES"
            configured = docker(["cmake", "-S", directory, "-B", "/evidence/build/freertos",
                       "-G", "Ninja", "-DCMAKE_TOOLCHAIN_FILE=/work/cmake/linux.cmake",
                       "-DCMAKE_C_COMPILER=gcc-14", "-DCMAKE_BUILD_TYPE=default_build", profile],
                       log="verification/freertos-configure.log")
            built = docker(["cmake", "--build", "/evidence/build/freertos", "--parallel", "4"],
                       log="verification/freertos-build.log")
            tested = docker(["ctest", "--test-dir", "/evidence/build/freertos", "--output-on-failure",
                       "--no-tests=error", "--timeout", "120", "--output-junit",
                       "/evidence/verification/freertos.xml"], log="verification/freertos-test.log", check=False)
            result["checks"].append({"name": "freertos", "profile": "TX_ENABLE_CONST_NAMES",
                 "status": "pass" if tested["exit_code"] == 0 else "fail", "configure": configured,
                 "build": built, "test": tested})
            if tested["exit_code"]:
                failures.append("FreeRTOS constant-name regression failed")
            write("verification.json", result)
            continue
        coverage = "ON" if suite in ["tx", "smp"] else "OFF"
        build = docker(["env", "TX_COVERAGE=" + coverage, "CTEST_REPEAT_FAIL=1", "CTEST_TIMEOUT=120",
                        "bash", f"scripts/build_{suite}.sh"], timeout=1800,
                       log=f"verification/{suite}-build.log")
        tests = docker(["env", "TX_COVERAGE=" + coverage, "CTEST_REPEAT_FAIL=1", "CTEST_TIMEOUT=120",
                        "bash", f"scripts/test_{suite}.sh"], timeout=2400,
                       log=f"verification/{suite}-test.log", check=False)
        result["checks"].append({"name": suite, "status": "pass" if tests["exit_code"] == 0 else "fail", "build": build, "test": tests})
        if tests["exit_code"]:
            failures.append(suite + " regression failed; see " + tests["log"])
        reports = EVIDENCE / "verification" / suite
        reports.mkdir(parents=True, exist_ok=True)
        for path in (SOURCE / directory / "build").glob("*/*.xml"):
            shutil.copy2(path, reports / (path.parent.name + "-" + path.name))
        if suite in ["tx", "smp"]:
            coverage_path = SOURCE / directory / "coverage_report/merged.xml"
            shutil.copy2(coverage_path, reports / "coverage-merged.xml")
            report = ET.parse(coverage_path).getroot()
            line_rate = float(report.attrib["line-rate"])
            lines = int(report.attrib["lines-valid"])
            result["checks"][-1]["coverage"] = {"line_rate": line_rate, "lines_valid": lines,
                                                   "branch_rate": report.attrib.get("branch-rate")}
            if lines == 0 or line_rate < 0.99:
                failures.append(suite + " coverage gate failed or report empty")
                result["checks"][-1]["status"] = "fail"
        write("verification.json", result)
        if suite == "smp" and tests["exit_code"]:
            baseline_smp_failure = reproduce_smp_baseline_failure(reports, baseline)
            # Preserve the actual failure; classify it for draft preparation only.
            result["checks"][-1]["status"] = "baseline-failure"
            result["checks"][-1]["baseline_reproduction"] = baseline_smp_failure
            failures.remove(suite + " regression failed; see " + tests["log"])
            write("verification.json", result)
    for name, args in [("ai-disclosure", ["bash", "scripts/check_ai_disclosure.sh"]),
                       ("port-consistency", ["bash", "scripts/check_ports.sh", "--no-regen"])]:
        measured = docker(args, timeout=600, log="verification/" + name + ".log")
        result["checks"].append({"name": name, "status": "pass", **measured})
    git("diff", "--check", base())
    if patch_hash() != frozen["patch_sha256"]:
        raise RuntimeError("Source changed while deterministic verification ran")
    if failures:
        result["errors"] = failures
        write("verification.json", result)
        raise RuntimeError("; ".join(failures))
    result["status"] = "prepared-with-baseline-failure" if baseline_smp_failure else "pass"
    result["local_validation_complete"] = baseline_smp_failure is None
    result["limitations"] = ["RISC-V, Arm GCC/clang, Cortex-M and FVP must be verified by upstream PR CI; not claimed locally",
                              "Local FreeRTOS uses GCC 14 with TX_ENABLE_CONST_NAMES; the stock default profile requires upstream CI",
                              "Generated-port regeneration is deferred to upstream CI; local check uses --no-regen on the uncommitted candidate",
                              "Hardware execution is not claimed", "Human contributor provenance review is pending"]
    if baseline_smp_failure:
        result["limitations"].append("Local SMP ERROR #7 occurred on both candidate and unchanged baseline; upstream final-head SMP CI is mandatory before requesting review or reporting merge readiness")
    write("verification.json", result)
    refresh_smp_diagnostic_index()
    print("Measured contribution preparation:", result["status"], result["patch_sha256"])


def refresh_smp_diagnostic_index():
    """Rebind only current results; retained historical failures stay intact."""
    path = EVIDENCE / "diagnostics/smp-retained-failures-index.json"
    if not path.exists():
        return
    index = json.loads(path.read_text())
    measured = read("verification.json")
    smp = next(item for item in measured["checks"] if item["name"] == "smp")
    def binding(name):
        return {"path": name, "sha256": hashlib.sha256((EVIDENCE / name).read_bytes()).hexdigest()}
    counts = []
    if smp["status"] == "pass":
        for report in sorted((EVIDENCE / "verification/smp").glob("*.xml")):
            if report.name == "coverage-merged.xml":
                continue
            cases = ET.parse(report).getroot().findall("testcase")
            if any(case.find("failure") is not None or case.find("error") is not None for case in cases):
                raise RuntimeError("Passing SMP record conflicts with its measured XML")
            counts.append(len(cases))
    index.update({"kernel_patch_sha256": measured["patch_sha256"],
        "generated_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "binding": {"freeze": binding("freeze.json"), "current_patch": binding("contribution.patch")},
        "current_verification": {"record": binding("verification.json"),
            "status": measured["status"], "smp_status": smp["status"],
            "smp_test_exit_code": smp["test"]["exit_code"],
            "smp_test_log": binding("verification/smp-test.log"),
            "smp_cpuset": measured["smp_host_cpus"],
            "all_passed_configuration_test_counts": counts,
            "total_tests_in_all_passed_summaries": sum(counts),
            "patch_sha256": measured["patch_sha256"],
            "distinction": "Current measured results are separate from retained historical failures. No historical failure or original baseline proof is rewritten."}})
    path.write_text(json.dumps(index, indent=2) + "\n")
    path.with_suffix(".json.sha256").write_text(hashlib.sha256(path.read_bytes()).hexdigest() + "\n")


def verification_prepared(verification):
    checks = {check["name"]: check for check in verification.get("checks", [])}
    expected = {"baseline": "expected-failure", "focused": "pass", "tx": "pass",
                "smp": "pass", "freertos": "pass", "ai-disclosure": "pass",
                "port-consistency": "pass", "license-headers": "pass"}
    if verification["status"] == "pass":
        return {name: checks.get(name, {}).get("status") for name in expected} == expected
    if verification["status"] != "prepared-with-baseline-failure":
        return False
    expected["smp"] = "baseline-failure"
    if ({name: checks.get(name, {}).get("status") for name in expected} != expected
            or verification.get("local_validation_complete") is not False):
        return False
    proof = checks["smp"].get("baseline_reproduction", {})
    if (proof.get("status") != "failed-on-candidate-and-unchanged-baseline"
            or proof.get("base_sha") != base()
            or proof.get("patch_sha256") != patch_hash()
            or proof.get("image_id") != IMAGE
            or proof.get("host_cpus") != verification.get("smp_host_cpus")
            or proof.get("unchanged_inputs") != ["common_smp", "ports_smp", "test/smp", "test/shared", "test/tx/regression", "cmake", "scripts"]):
        return False
    candidate_failures = proof.get("candidate_failures", [])
    if not candidate_failures or any(
            item.get("assertion") != "ERROR #7"
            or item.get("test", "").split("::")[-1] != "threadx_smp_random_resume_suspend_exclusion_pt_test"
            for item in candidate_failures):
        return False
    configurations = {item["test"].split("::")[0] for item in candidate_failures}
    reproduced = {item.get("configuration") for item in proof.get("baseline_runs", [])
                  if item.get("exit_code") == 1}
    return configurations == reproduced


def review_gate():
    frozen = read("freeze.json")
    verification = read("verification.json")
    if (PACKAGE / "execution-manifest.json").exists():
        if (verification.get("driver_sha256") != hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
                or verification.get("image_id") != IMAGE):
            raise RuntimeError("Verification belongs to a different immutable runner or verification image")
    if patch_hash() != frozen["patch_sha256"] or verification["patch_sha256"] != patch_hash() or not verification_prepared(verification):
        raise RuntimeError("Frozen verification evidence is absent or stale")
    for name in ["technical-review.json", "process-review.json"]:
        review = read(name)
        if review["patch_sha256"] != patch_hash() or review["verdict"] != "pass":
            raise RuntimeError("Independent review rejected current patch: " + name)
        if any(f["severity"].lower() in ["blocking", "critical", "high"] for f in review["findings"]):
            raise RuntimeError("Unresolved blocking review finding: " + name)
    docs_verify_record = read("docs-verification.json")
    docs_review = read("documentation-review.json")
    if docs_verify_record["status"] != "pass" or docs_verify_record["patch_sha256"] != docs_hash() or docs_review["verdict"] != "pass" or docs_review["patch_sha256"] != docs_hash():
        raise RuntimeError("Required companion documentation is unverified or stale")
    if any(f["severity"].lower() in ["blocking", "critical", "high"] for f in docs_review["findings"]):
        raise RuntimeError("Companion documentation has a blocking review finding")
    write("review-gate.json", {"status": "pass", "patch_sha256": patch_hash(),
                                "human_provenance_review": "confirmed" if consent_ready() else "pending"})
    print(json.dumps({"outcome": "succeeded", "context_updates": {"consent_ready": consent_ready()}}))


def human_header_paths():
    paths = sorted({*(SOURCE / FOCUSED).rglob("*.c"),
                    *(SOURCE / TEST_SOURCES).rglob("*.c")})
    return [*paths, SOURCE / FOCUSED / "CMakeLists.txt"]


def human_header_forms(path):
    continuation = " * " if path.suffix == ".c" else "# "
    return ("Human provenance review and\n" + continuation + "verification are pending.",
            "The human contributor has\n" + continuation + "reviewed and verified that the code is correct.")


def human_review_matches_current(review):
    return (review.get("confirmed") is True
            and review.get("patch_sha256") == patch_hash()
            and review.get("docs_patch_sha256") == docs_hash())


def consent_ready():
    if not (EVIDENCE / "human-review.json").exists():
        return False
    review = read("human-review.json")
    if not human_review_matches_current(review) or not review.get("finalized_at"):
        return False
    recorded = review.get("finalized_header_sha256", {})
    paths = human_header_paths()
    if len(paths) < 2:
        return False
    for path in paths:
        if not path.is_file():
            return False
        content = path.read_text()
        pending, canonical = human_header_forms(path)
        if pending in content or content.count(canonical) != 1:
            return False
        if recorded.get(str(path.relative_to(SOURCE))) != hashlib.sha256(path.read_bytes()).hexdigest():
            return False
    return set(recorded) == {str(path.relative_to(SOURCE)) for path in paths}


def prepare_human_review():
    review_gate()
    digest = patch_hash()
    docs_digest = docs_hash()
    write("human-review-target.json", {"patch_sha256": digest, "docs_patch_sha256": docs_digest})
    request_text = (
        f"# Human contribution review for ThreadX #744\n\nKernel patch SHA-256: `{digest}`\n\nCompanion docs patch SHA-256: `{docs_digest}`\n\n"
        "Read contribution.patch AND docs-contribution.patch, both proposed PR bodies, measured verification, and the independent reviews. "
        "ThreadX CONTRIBUTING.md requires the submitting human to review and understand AI output, verify its correctness, and confirm the right to contribute it. "
        "The candidate's new-file headers honestly state human review is pending. After your confirmation, only that statement will be changed to the guide's reviewed wording, and the resulting patch will be frozen, tested and independently reviewed again. Any substantive repair requires another human review.\n\n"
        "Your response also confirms the commit email covered by your signed Eclipse ECA. "
        "Eclipse account username: jnascimento6p0. The final PR ECA check must still validate the email.\n\n"
        f"If these statements are true, reply exactly: `REVIEWED {digest} <your ECA commit email>`\n\n"
        "Publication follows only after confirmation and successful final verification. No agent may provide this response on your behalf.\n\n"
        "Source: https://github.com/eclipse-threadx/threadx/blob/" + base() + "/CONTRIBUTING.md#ai-assisted-contributions\n"
    )
    (EVIDENCE / "human-review-request.md").write_text(request_text)
    write("readiness.json", {"status": "awaiting-human-review", "patch_sha256": digest,
          "blockers": ["Human contributor review and provenance confirmation required before publication",
                       "Final-head Eclipse/CI checks and upstream human approval remain pending"]})
    texts = [("Review request", request_text), ("Proposed PR", (EVIDENCE / "pr-body.md").read_text()),
             ("Patch", (EVIDENCE / "contribution.patch").read_text()),
             ("Companion documentation patch", (EVIDENCE / "docs-contribution.patch").read_text()),
             ("Companion documentation PR", (EVIDENCE / "docs-pr-body.md").read_text()),
             ("Measured checks", (EVIDENCE / "verification.json").read_text()),
             ("Technical review", (EVIDENCE / "technical-review.json").read_text()),
             ("Process review", (EVIDENCE / "process-review.json").read_text())]
    document = '<!doctype html><html lang="en"><meta charset="utf-8"><title>ThreadX 744 contribution review</title><style>body{font:16px system-ui;max-width:1100px;margin:3em auto;padding:0 1em}pre{white-space:pre-wrap;background:#f4f4f4;padding:1em}h1{font-size:1.5em}</style>'
    for label, content in texts:
        document += '<h1>' + html.escape(label) + '</h1><pre>' + html.escape(content) + '</pre>'
    REPO_ARTIFACTS.mkdir(parents=True, exist_ok=True)
    (REPO_ARTIFACTS / "review.html").write_text(document + '</html>\n')
    export(require_ready=False)
    print(json.dumps({"outcome": "succeeded", "context_updates": {"review_target": {
        "label": "ThreadX #744: review patch " + digest,
        "url": "http://127.0.0.1:32278/review.html", "kind": "document"}}}))


def record_human_review():
    response = sys.stdin.read().strip()
    matched = re.fullmatch(r"REVIEWED ([0-9a-f]{64}) ([^\s@]+@[^\s@]+\.[^\s@]+)", response)
    if not matched or matched.group(1) != patch_hash():
        raise RuntimeError("Expected an actual human REVIEWED response with the current patch digest and ECA commit email; automatic approval is invalid")
    review_gate()
    target = read("human-review-target.json")
    if target["patch_sha256"] != patch_hash() or target["docs_patch_sha256"] != docs_hash():
        raise RuntimeError("Review dossier changed while awaiting the human response")
    write("human-review.json", {"confirmed": True, "reviewed_patch_sha256": matched.group(1),
          "patch_sha256": matched.group(1), "author_email": matched.group(2),
          "docs_patch_sha256": target["docs_patch_sha256"],
          "eclipse_username": "jnascimento6p0", "response": response, "at": time.time(),
          "approved_delta": "Only canonical human-reviewed wording in the candidate new-file AI headers; final verification and independent review required"})


def finalize_human_header():
    receipt = read("human-review.json")
    if not human_review_matches_current(receipt):
        raise RuntimeError("No human review applies to both current candidates")
    original_digest = patch_hash()
    paths = human_header_paths()
    if len(paths) < 2 or any(not path.is_file() for path in paths):
        raise RuntimeError("Expected reviewed C and CMake AI headers are absent")
    frozen_files = read("freeze.json")["files"]
    original_files = {name: (SOURCE / name).read_bytes() for name in frozen_files}
    modified = []
    edits = []
    for path in paths:
        content = path.read_text()
        pending, canonical = human_header_forms(path)
        if content.count(pending) == 1 and canonical not in content:
            edits.append((path, content.replace(pending, canonical, 1)))
            modified.append(str(path.relative_to(SOURCE)))
        elif pending in content or content.count(canonical) != 1:
            raise RuntimeError("Candidate AI header needs an explicitly reviewed canonical transformation: " + str(path))
    if patch_hash() != original_digest or not human_review_matches_current(receipt):
        raise RuntimeError("Reviewed source changed before header finalization")
    for path, content in edits:
        path.write_text(content)
    expected_files = dict(original_files)
    expected_files.update({str(path.relative_to(SOURCE)): content.encode() for path, content in edits})
    if (git("diff", "--name-only", base()).splitlines() != frozen_files
            or any((SOURCE / name).read_bytes() != content for name, content in expected_files.items())
            or docs_hash() != receipt["docs_patch_sha256"]):
        raise RuntimeError("Header finalization changed more than the approved canonical wording")
    receipt["finalized_header_files"] = modified
    receipt["finalized_header_sha256"] = {
        str(path.relative_to(SOURCE)): hashlib.sha256(path.read_bytes()).hexdigest() for path in paths}
    receipt["patch_sha256"] = patch_hash()
    receipt["finalized_at"] = time.time()
    write("human-review.json", receipt)
    admission = read("admission.json")
    admission["author_email"] = receipt["author_email"]
    write("admission.json", admission)
    git("config", "user.email", receipt["author_email"])


def docs_verify():
    admission = read("docs-admission.json")
    path = "rtos-docs/threadx/modules/ROOT/pages/chapter4.adoc"
    files = run(["git", "diff", "--name-only", admission["base_sha"]], cwd=DOCS).stdout.decode().splitlines()
    if files != [path]:
        raise RuntimeError("Companion documentation must be the scoped tx_thread_create clarification")
    run(["git", "diff", "--check", admission["base_sha"]], cwd=DOCS)
    data = run(["git", "diff", "--binary", admission["base_sha"]], cwd=DOCS).stdout
    (EVIDENCE / "docs-contribution.patch").write_bytes(data)
    digest = docs_hash()
    write("docs-freeze.json", {"patch_sha256": digest, "base_sha": admission["base_sha"], "files": files})
    write("docs-verification.json", {"patch_sha256": digest, "status": "fail"})
    env = os.environ.copy()
    env["npm_config_cache"] = str(EVIDENCE / "npm-cache")
    env["TMPDIR"] = str(EVIDENCE / "tmp")
    run(["npm", "install", "--package-lock=false", "--no-audit", "--no-fund"], cwd=DOCS, timeout=1200, env=env, log="documentation/install.log")
    output = EVIDENCE / "docs-html"
    if output.exists():
        shutil.rmtree(output)
    run(["npm", "run", "build:html", "--", "--to-dir", str(output)], cwd=DOCS, timeout=1200, env=env, log="documentation/render.log")
    pages = list(output.glob("threadx/*/chapter4.html"))
    if not pages or not any("These adjustments preserve the full address" in p.read_text() for p in pages):
        raise RuntimeError("Antora did not render the candidate stack-address paragraph")
    if docs_hash() != digest:
        raise RuntimeError("Documentation changed during verification")
    write("docs-verification.json", {"patch_sha256": digest, "status": "pass", "rendered_pages": [str(p) for p in pages],
          "limitations": ["No automatic Antora pull_request workflow exists; PDF and upstream maintainer review remain unclaimed"]})
    refresh_docs_pr_text()


def refresh_docs_pr_text():
    body_path = EVIDENCE / "docs-pr-body.md"
    body = body_path.read_text()
    verification = read("docs-verification.json")
    if verification["status"] == "pass" and verification["patch_sha256"] == docs_hash():
        body = body.replace("Antora rendering is pending until deterministic `docs-verify` executes.",
            "The candidate rendered successfully with Antora; the generated tx_thread_create page contains the added paragraph.")
    if (EVIDENCE / "documentation-review.json").exists():
        review = read("documentation-review.json")
        if review["verdict"] == "pass" and review["patch_sha256"] == docs_hash():
            body = body.replace("Independent review and human technical and provenance review are pending; no approval is claimed.",
                "The independent documentation review passed on this patch. Human technical and provenance review and upstream approval remain pending.")
    if consent_ready():
        body = body.replace("Human technical and provenance review and upstream approval remain pending.",
            "Human technical and provenance review was confirmed for this patch. Upstream approval and final-head ECA checks remain pending.")
    body_path.write_text(body)


def assert_publishing_identity(cwd, committed=False):
    admission = read("admission.json")
    receipt = read("human-review.json")
    current_user = gh_json("api", "user")
    if current_user.get("login", "").lower() != admission["author_login"].lower():
        raise RuntimeError("Authenticated GitHub identity differs from the admitted contributor")
    if committed:
        email = run(["git", "log", "-1", "--format=%ae"], cwd=cwd).stdout.decode().strip()
    else:
        identity = run(["git", "var", "GIT_AUTHOR_IDENT"], cwd=cwd).stdout.decode().strip()
        match = re.fullmatch(r".* <([^<>]+)> [0-9]+ [+-][0-9]{4}", identity)
        if not match:
            raise RuntimeError("Git author identity cannot be verified")
        email = match.group(1)
    if email != receipt["author_email"]:
        raise RuntimeError("Actual Git author email differs from the human-confirmed ECA email")


def verified_docs_publication():
    publication = read("docs-publication.json")
    admission = read("docs-admission.json")
    receipt = read("human-review.json")
    head = run(["git", "rev-parse", "HEAD"], cwd=DOCS).stdout.decode().strip()
    if (publication.get("patch_sha256") != docs_hash()
            or publication.get("patch_sha256") != receipt.get("docs_patch_sha256")
            or publication.get("head_sha") != head
            or publication.get("base_branch") != admission["base_branch"]
            or publication.get("base_sha") != admission["base_sha"]):
        raise RuntimeError("Companion publication does not match the reviewed documentation hash, head and base")
    expected_prefix = "https://github.com/" + admission["upstream"] + "/pull/"
    url = publication.get("url", "")
    if not url.startswith(expected_prefix) or not url[len(expected_prefix):].isdigit():
        raise RuntimeError("Companion publication URL is not an upstream documentation pull request")
    pr = gh_json("pr", "view", url, "--json", "url,headRefOid,baseRefName")
    if (pr.get("url") != url or pr.get("headRefOid") != head
            or pr.get("baseRefName") != admission["base_branch"]):
        raise RuntimeError("Remote companion PR differs from its reviewed documentation head or base")
    return publication


def publish():
    review_gate()
    attestation_path = EVIDENCE / "human-review.json"
    if not attestation_path.exists():
        prepare_human_review()
        raise RuntimeError("ThreadX CONTRIBUTING.md requires human provenance review before submission; tested patch and PR text await contributor review")
    attestation = read("human-review.json")
    if not consent_ready():
        raise RuntimeError("Both patches require current human consent and completed canonical header finalization")
    check_license_headers("publication")
    title = (EVIDENCE / "pr-title.txt").read_text().strip()
    if len(title) > 72 or not title.startswith(("Fixed ", "Preserved ", "Corrected ")):
        raise RuntimeError("PR title must be a past-tense statement within 72 characters")
    body = (EVIDENCE / "pr-body.md").read_text()
    if "744" not in body or "gpt-6.1-sol" not in body:
        raise RuntimeError("PR body must reference issue and actual model")
    admission = read("admission.json")
    # Publish the separately reviewed companion first, then link its real URL.
    if not (EVIDENCE / "docs-publication.json").exists():
        docs_admission = read("docs-admission.json")
        docs_title = (EVIDENCE / "docs-pr-title.txt").read_text().strip()
        if not docs_title.startswith("Documented ") or len(docs_title) > 72:
            raise RuntimeError("Companion title must be past tense within 72 characters")
        for key, value in [("user.name", admission["author_name"] or admission["author_login"]),
                           ("user.email", attestation["author_email"])]:
            run(["git", "config", key, value], cwd=DOCS)
        assert_publishing_identity(DOCS)
        run(["git", "add", "--", *read("docs-freeze.json")["files"]], cwd=DOCS)
        docs_message = docs_title + "\n\nStack checking adjusted stack addresses without documenting pointer width.\n\nClarified alignment, checking reserves, and full-width pointer preservation.\n\nThe candidate rendered successfully with Antora and passed independent review.\n\nAssisted-by: Codex (gpt-6.1-sol) <noreply@openai.com>\n"
        (EVIDENCE / "docs-commit-message.txt").write_text(docs_message)
        run(["git", "commit", "-F", str(EVIDENCE / "docs-commit-message.txt")], cwd=DOCS)
        if docs_hash() != attestation["docs_patch_sha256"]:
            raise RuntimeError("Documentation commit changed the human-reviewed patch")
        assert_publishing_identity(DOCS, committed=True)
        run(["gh", "repo", "fork", docs_admission["upstream"], "--clone=false"], timeout=120, log="publication/docs-fork.log")
        run(["git", "push", "https://github.com/" + admission["author_login"] + "/rtos-docs-asciidoc.git",
             "HEAD:refs/heads/" + docs_admission["branch"]], cwd=DOCS, timeout=120, log="publication/docs-push.log")
        refresh_docs_pr_text()
        docs_body = (EVIDENCE / "docs-pr-body.md").read_text()
        docs_body = docs_body.replace("pending human review", "human contributor review confirmed")
        (EVIDENCE / "docs-pr-body-published.md").write_text(docs_body + "\nThe human contributor reviewed both linked contribution patches and confirmed provenance before submission.\n")
        created_docs = run(["gh", "pr", "create", "--repo", docs_admission["upstream"], "--base", "main",
            "--head", admission["author_login"] + ":" + docs_admission["branch"], "--draft", "--title", docs_title,
            "--body-file", str(EVIDENCE / "docs-pr-body-published.md")], timeout=120)
        write("docs-publication.json", {"url": created_docs.stdout.decode().strip(),
              "head_sha": run(["git", "rev-parse", "HEAD"], cwd=DOCS).stdout.decode().strip(),
              "patch_sha256": docs_hash(), "base_branch": docs_admission["base_branch"],
              "base_sha": docs_admission["base_sha"], "human_provenance_review": "confirmed"})
    docs_url = verified_docs_publication()["url"]
    assert_publishing_identity(DOCS, committed=True)
    (EVIDENCE / "pr-body.md").write_text(body + "\nMatching documentation: " + docs_url + ".\n")
    git("config", "user.name", admission["author_name"] or admission["author_login"])
    git("config", "user.email", attestation["author_email"])
    assert_publishing_identity(SOURCE)
    git("add", "--", *read("freeze.json")["files"])
    measured_summary = ("Focused and single-core checks passed. Local SMP ERROR #7 also occurred\n"
                        "on the unchanged baseline; final-head upstream SMP CI remains required.\n"
                        if read("verification.json")["status"] == "prepared-with-baseline-failure" else
                        "The frozen patch passed recorded focused and host regression checks.\n")
    message = "Fixed MISRA stack alignment on ports with 64-bit pointers\n\n" + \
              "MISRA stack checking converted the stack address through 32-bit ULONG.\n\n" + \
              "Preserved ALIGN_TYPE width in both stack-alignment conversions. Added a\n" + \
              "native-width behavioral regression that fails on the original code.\n\n" + \
              measured_summary + \
              "The human contributor reviewed and confirmed the contribution.\n\n" + \
              "Fixes: eclipse-threadx/threadx#744\n" + \
              "Assisted-by: Codex (gpt-6.1-sol) <noreply@openai.com>\n"
    (EVIDENCE / "commit-message.txt").write_text(message)
    git("commit", "-F", str(EVIDENCE / "commit-message.txt"))
    if patch_hash() != read("freeze.json")["patch_sha256"]:
        raise RuntimeError("Commit differs from independently reviewed patch")
    assert_publishing_identity(SOURCE, committed=True)
    run(["gh", "repo", "fork", UPSTREAM, "--clone=false"], timeout=120,
        log="publication/fork.log")
    fork = admission["author_login"] + "/threadx"
    run(["git", "push", "https://github.com/" + fork + ".git", "HEAD:refs/heads/" + admission["branch"]],
        timeout=120, log="publication/push.log")
    created = run(["gh", "pr", "create", "--repo", UPSTREAM, "--base", "dev", "--head",
                   admission["author_login"] + ":" + admission["branch"], "--draft", "--title", title,
                   "--body-file", str(EVIDENCE / "pr-body.md")], timeout=120)
    url = created.stdout.decode().strip()
    write("publication.json", {"url": url, "head_sha": git("rev-parse", "HEAD"),
          "patch_sha256": patch_hash(), "draft": True, "human_provenance_review": "confirmed"})
    print(url)


def current_required_checks():
    rules = gh_json("api", f"repos/{UPSTREAM}/rules/branches/dev")
    write("upstream-rules-final.json", rules)
    return [s["context"] for r in rules if r["type"] == "required_status_checks"
            for s in r["parameters"]["required_status_checks"]]


def documentation_approval_blockers(pr):
    if pr.get("reviewDecision") == "CHANGES_REQUESTED":
        return ["Upstream documentation changes are requested"]
    if pr.get("reviewDecision") == "APPROVED":
        return []
    upstream = read("docs-admission.json")["upstream"]
    number = pr["url"].rstrip("/").rsplit("/", 1)[1]
    try:
        pages = gh_json("api", "--paginate", "--slurp", f"repos/{upstream}/pulls/{number}/reviews")
        reviews = [review for page in pages for review in page]
    except (RuntimeError, TypeError, ValueError) as error:
        return ["Companion reviewer authority could not be verified: " + str(error)]
    latest = {}
    for review in sorted(reviews, key=lambda r: r.get("id", 0)):
        login = review.get("user", {}).get("login")
        if login and review.get("state") in ["APPROVED", "CHANGES_REQUESTED", "DISMISSED"]:
            latest[login] = review
    authority = []
    approved = False
    requested = False
    for login, review in latest.items():
        try:
            permission = gh_json("api", f"repos/{upstream}/collaborators/{login}/permission")
            authorized = permission.get("permission") in ["admin", "write"]
        except RuntimeError as error:
            authority.append({"login": login, "verified": False, "error": str(error)})
            continue
        authority.append({"login": login, "permission": permission.get("permission"),
                          "role_name": permission.get("role_name"), "review_id": review["id"],
                          "state": review["state"], "commit_id": review.get("commit_id")})
        if authorized and review["state"] == "CHANGES_REQUESTED":
            requested = True
        if authorized and review["state"] == "APPROVED" and review.get("commit_id") == pr["headRefOid"]:
            approved = True
    write("docs-review-authority.json", authority)
    if requested:
        return ["An authorized upstream documentation reviewer requested changes"]
    if any(item.get("verified") is False for item in authority):
        return ["Companion reviewer authority could not be verified"]
    if not approved:
        return ["Verified upstream maintainer approval of the companion head is pending"]
    return []


def monitor_docs():
    write("docs-readiness.json", {"status": "blocked", "blockers": ["Current companion PR checks have not completed"],
                                 "checked_at": time.time()})
    publication = verified_docs_publication()
    fields = "url,isDraft,headRefOid,baseRefName,reviewDecision,mergeStateStatus,mergeable,statusCheckRollup,reviews"
    pr = gh_json("pr", "view", publication["url"], "--json", fields)
    if pr["headRefOid"] != publication["head_sha"]:
        raise RuntimeError("Documentation PR head differs from its reviewed publication")
    checks = pr["statusCheckRollup"] or []
    states = {c.get("name", c.get("context")): c.get("conclusion", c.get("state")) for c in checks}
    blockers = []
    if not consent_ready():
        blockers.append("Current human review or canonical header finalization is absent or stale")
    if states.get("eclipsefdn/eca") != "SUCCESS":
        blockers.append("Final-head Eclipse ECA check is not passing")
    for c in checks:
        if c.get("status", "COMPLETED") != "COMPLETED" or c.get("state") in ["PENDING", "FAILURE", "ERROR"] or c.get("conclusion") in ["FAILURE", "CANCELLED", "TIMED_OUT", "ACTION_REQUIRED"]:
            blockers.append("Applicable documentation check is not passing: " + c.get("name", c.get("context", "unknown")))
    if pr["isDraft"] and not blockers and consent_ready():
        run(["gh", "pr", "ready", publication["url"]], timeout=120, log="publication/docs-ready-for-review.log")
        return monitor_docs()
    if pr["isDraft"]:
        blockers.append("Documentation PR remains a draft")
    blockers.extend(documentation_approval_blockers(pr))
    if pr["baseRefName"] != read("docs-admission.json")["base_branch"] or pr["mergeable"] != "MERGEABLE" or pr.get("mergeStateStatus") != "CLEAN":
        blockers.append("Documentation protected-branch merge state/base is not satisfied")
    write("docs-pr-status.json", pr)
    write("docs-readiness.json", {"status": "ready" if not blockers else "blocked", "blockers": blockers,
          "head_sha": pr["headRefOid"], "url": pr["url"], "checked_at": time.time()})
    return blockers


def verify_kernel_publication(publication):
    frozen = read("freeze.json")
    receipt = read("human-review.json")
    digest = patch_hash()
    if (publication.get("patch_sha256") != digest or frozen.get("patch_sha256") != digest
            or receipt.get("patch_sha256") != digest
            or publication.get("head_sha") != git("rev-parse", "HEAD")):
        raise RuntimeError("Kernel publication differs from the current frozen human-reviewed patch or local HEAD")
    expected_prefix = "https://github.com/" + UPSTREAM + "/pull/"
    url = publication.get("url", "")
    if not url.startswith(expected_prefix) or not url[len(expected_prefix):].isdigit():
        raise RuntimeError("Kernel publication URL is not an upstream ThreadX pull request")


def current_workflow_runs(head_sha):
    actions = gh_json("api", "--paginate", "--slurp",
                      f"repos/{UPSTREAM}/actions/runs?head_sha={head_sha}&per_page=100")
    workflow_runs = [item for page in actions for item in page.get("workflow_runs", [])
                     if item.get("head_sha") == head_sha]
    write("upstream-actions-final-head.json", {"head_sha": head_sha,
          "workflow_runs": workflow_runs, "checked_at": time.time()})
    return workflow_runs


def monitor():
    publication = read("publication.json")
    snapshot_blockers = []
    if not consent_ready():
        snapshot_blockers.append("Current human review or canonical header finalization is absent or stale")
    try:
        verify_kernel_publication(publication)
    except (RuntimeError, KeyError, FileNotFoundError) as error:
        snapshot_blockers.append(str(error))
    # A remote lookup failure must not leave an earlier ready assessment active.
    write("readiness.json", {"status": "blocked", "blockers": snapshot_blockers or ["Final-head PR checks have not completed"],
          "head_sha": publication.get("head_sha"), "url": publication.get("url"), "checked_at": time.time()})
    fields = "number,url,isDraft,headRefOid,baseRefName,reviewDecision,mergeStateStatus,mergeable,statusCheckRollup,reviews"
    for attempt in range(60):
        pr = gh_json("pr", "view", publication["url"], "--json", fields)
        write("pr-status.json", pr)
        if pr["headRefOid"] != publication["head_sha"]:
            raise RuntimeError("PR head differs from the reviewed publication")
        checks = pr["statusCheckRollup"] or []
        if checks and all(c.get("status", "COMPLETED") == "COMPLETED" and c.get("state") != "PENDING" for c in checks):
            break
        time.sleep(15)
    workflow_runs = current_workflow_runs(publication["head_sha"])
    required = current_required_checks()
    passed = {c.get("name", c.get("context")): c.get("conclusion", c.get("state")) for c in checks}
    blockers = list(snapshot_blockers)
    for workflow_run in workflow_runs:
        conclusion = workflow_run.get("conclusion")
        if conclusion in ["action_required", "failure", "cancelled", "timed_out", "startup_failure"]:
            blockers.append("Upstream workflow " + workflow_run.get("name", "unknown")
                            + " requires action: " + conclusion)
        elif workflow_run.get("status") != "completed":
            blockers.append("Upstream workflow is still pending: " + workflow_run.get("name", "unknown"))
    # A disclosed local baseline failure never waives executed final-head SMP CI,
    # even if the branch-rule context list changes after admission.
    if passed.get("smp / run_tests") != "SUCCESS":
        blockers.append("Final-head SMP regression CI has not executed successfully")
    if passed.get("eclipsefdn/eca") != "SUCCESS":
        blockers.append("Final-head Eclipse ECA check is not passing")
    for name in required:
        if passed.get(name) not in ["SUCCESS", "NEUTRAL"]:
            blockers.append("Required check not passing: " + name)
    for c in checks:
        if c.get("conclusion") in ["FAILURE", "CANCELLED", "TIMED_OUT", "ACTION_REQUIRED"] or c.get("state") in ["FAILURE", "ERROR"]:
            blockers.append("Applicable check failed or needs action: " + c.get("name", c.get("context", "unknown")))
        elif c.get("status", "COMPLETED") != "COMPLETED" or c.get("state") in ["PENDING", "EXPECTED"]:
            blockers.append("Applicable check is still pending: " + c.get("name", c.get("context", "unknown")))
    if pr["isDraft"] and not blockers and consent_ready():
        run(["gh", "pr", "ready", publication["url"]], timeout=120, log="publication/ready-for-review.log")
        pr = gh_json("pr", "view", publication["url"], "--json", fields)
        if pr["headRefOid"] != publication["head_sha"]:
            raise RuntimeError("PR head changed while marking ready for review")
        write("pr-status.json", pr)
        return monitor()
    if pr["isDraft"]:
        blockers.append("PR remains a draft")
    if pr["reviewDecision"] != "APPROVED":
        blockers.append("Required upstream human/code-owner approval is pending")
    if pr["baseRefName"] != "dev" or pr["mergeable"] != "MERGEABLE":
        blockers.append("GitHub mergeability/base branch gate is not satisfied")
    if pr.get("mergeStateStatus") != "CLEAN":
        blockers.append("GitHub protected-branch merge state is not clean: " + str(pr.get("mergeStateStatus")))
    if not (EVIDENCE / "docs-publication.json").exists():
        blockers.append("Required companion documentation publication is absent")
    else:
        try:
            blockers.extend("Companion docs: " + item for item in monitor_docs())
        except (RuntimeError, KeyError, FileNotFoundError) as error:
            blockers.append("Companion docs publication could not be verified: " + str(error))
    write("readiness.json", {"status": "ready" if not blockers else "blocked", "blockers": blockers,
          "head_sha": pr["headRefOid"], "url": pr["url"], "merge_state": pr.get("mergeStateStatus"), "checked_at": time.time()})
    print("PR readiness:", "ready" if not blockers else "blocked", blockers)


def export(require_ready=True):
    REPO_ARTIFACTS.mkdir(exist_ok=True, parents=True)
    names = ["admission.json", "issue.json", "dependencies.json", "agent-settings.json", "freeze.json",
             "contribution.patch", "verification.json", "technical-review.json", "process-review.json",
             "review-gate.json", "pr-title.txt", "pr-body.md", "commit-message.txt", "publication.json",
             "pr-status.json", "readiness.json", "last-error.json", "upstream-rules.json", "eca-verification.json"]
    names += ["implementation-plan.md", "implementation-notes.md", "human-review.json", "human-review-request.md", "upstream-rules-final.json"]
    names += ["smp-baseline-reproduction.json", "license-headers.json", "license-headers-final.json"]
    names += ["docs-admission.json", "docs-contribution.patch", "docs-freeze.json", "docs-verification.json", "documentation-review.json", "docs-pr-title.txt", "docs-pr-body.md", "human-review-target.json"]
    names += ["docs-publication.json", "docs-pr-status.json", "docs-readiness.json", "docs-commit-message.txt", "docs-pr-body-published.md", "docs-review-authority.json", "upstream-actions-final-head.json"]
    for name in names:
        if (EVIDENCE / name).exists():
            shutil.copy2(EVIDENCE / name, REPO_ARTIFACTS / name)
    logs = EVIDENCE / "verification"
    if logs.exists():
        shutil.copytree(logs, REPO_ARTIFACTS / "verification", dirs_exist_ok=True)
    for name in ["documentation", "diagnostics"]:
        if (EVIDENCE / name).exists():
            shutil.copytree(EVIDENCE / name, REPO_ARTIFACTS / name, dirs_exist_ok=True,
                ignore=shutil.ignore_patterns("*-build", "CMakeFiles", "__pycache__", "*.pyc"))
    manifest = []
    for path in sorted(REPO_ARTIFACTS.rglob("*")):
        if path.is_file() and path.name != "manifest.json":
            manifest.append({"path": str(path.relative_to(REPO_ARTIFACTS)), "sha256": hashlib.sha256(path.read_bytes()).hexdigest(), "bytes": path.stat().st_size})
    (REPO_ARTIFACTS / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    readiness = read("readiness.json") if (EVIDENCE / "readiness.json").exists() else {"status": "incomplete", "blockers": ["No final PR readiness assessment"]}
    print("Exported contribution artifacts:", REPO_ARTIFACTS)
    if require_ready and readiness["status"] != "ready":
        raise RuntimeError("Artifacts exported; contribution is not yet ready to merge: " + json.dumps(readiness["blockers"]))


def validate_execution_binding():
    """Reject changed runner/prompts in a registered, content-addressed bundle."""
    manifest_path = PACKAGE / "execution-manifest.json"
    if not manifest_path.exists():
        if PACKAGE != Path("/home/jefferson/Thinking_CAPs/contributions/threadx-744/workflow"):
            raise RuntimeError("Registered execution bundle lacks its manifest")
        return
    manifest = json.loads(manifest_path.read_text())
    hashes = manifest["files"]
    digest = hashlib.sha256(json.dumps(hashes, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    if digest != PACKAGE.name or digest != manifest["bundle_sha256"]:
        raise RuntimeError("Execution manifest does not match its content-addressed directory")
    for name, expected in hashes.items():
        if hashlib.sha256((PACKAGE / name).read_bytes()).hexdigest() != expected:
            raise RuntimeError("Execution bundle changed: " + name)
    if manifest["image_id"] != IMAGE:
        raise RuntimeError("Verification image differs from registered execution binding")


if __name__ == "__main__":
    actions = {"admit": admit, "freeze": freeze, "verify": verify, "review-gate": review_gate,
               "publish": publish, "monitor": monitor, "export": export,
               "prepare-human-review": prepare_human_review, "record-human-review": record_human_review,
               "finalize-human-header": finalize_human_header, "docs-verify": docs_verify}
    try:
        validate_execution_binding()
        if sys.argv[1] == "agent":
            agent(sys.argv[2])
        else:
            actions[sys.argv[1]]()
    except Exception as error:
        write("last-error.json", {"action": sys.argv[1:], "error": str(error), "at": time.time()})
        print(str(error), file=sys.stderr)
        sys.exit(1)
