#!/usr/bin/env python3
# Copyright (c) 2026 Eclipse SDV Hackathon Team
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).
# The AI-generated portions may be considered public domain (CC0-1.0).
# Human provenance review and verification are pending.
#
# SPDX-License-Identifier: Apache-2.0 AND CC0-1.0

"""Audit contribution headers without editing sources or asserting human consent.

Policies: Eclipse Project Handbook #ip-copyright-headers and ThreadX
CONTRIBUTING.md #ai-assisted-contributions. Licenses follow each project;
Eclipse membership does not imply EPL licensing.
"""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

POLICY_SOURCES = [
    "https://www.eclipse.org/projects/handbook/#ip-copyright-headers",
    "https://github.com/eclipse-threadx/threadx/blob/dev/CONTRIBUTING.md#ai-assisted-contributions",
]
LOCAL_EXTENSIONS = {".py", ".fabro", ".toml", ".c", ".S", ".h", ".sh", ".cpp"}
LOCAL_FILENAMES = {"Dockerfile", "CMakeLists.txt"}
GENERATED_PARTS = {"CMakeFiles", "__pycache__", "node_modules", "_deps", "coverage_report", "docs-html"}
SNAPSHOT_PARTS = {"upstream-process", "upstream-snapshot", "upstream-snapshots"}
PENDING = "Human provenance review and verification are pending."
REVIEWED = "The human contributor has reviewed and verified that the code is correct."


def leading_header(text):
    """Return only leading comments, limited to the first sixty physical lines."""
    collected = []
    block = None
    for number, line in enumerate(text.splitlines()[:60]):
        stripped = line.strip()
        if number == 0 and stripped.startswith("#!"):
            continue
        if block:
            collected.append(line)
            closing = "*/" if block == "c" else "////"
            if closing in stripped:
                block = None
                if closing == "*/" and stripped.split(closing, 1)[1].strip():
                    break
            continue
        if not stripped:
            continue
        if stripped.startswith("/*"):
            collected.append(line)
            if "*/" not in stripped:
                block = "c"
            elif stripped.split("*/", 1)[1].strip():
                break
        elif stripped == "////":
            collected.append(line)
            block = "adoc"
        elif stripped.startswith(("#", "//")):
            collected.append(line)
        else:
            break
    return "\n".join(collected)


def clean_line(line):
    return re.sub(r"^(?:/\*+|//|#|\*)\s*", "", line.strip()).removesuffix("*/").strip()


def prose(header):
    return " ".join(clean_line(line) for line in header.splitlines() if clean_line(line))


def copyright_lines(header):
    return [clean_line(line) for line in header.splitlines() if "Copyright" in line]


def spdx_expressions(header):
    expressions = []
    for line in header.splitlines():
        found = re.fullmatch(r"SPDX-License-Identifier:\s*(.+)", clean_line(line))
        if found:
            expressions.append(re.sub(r"\band\b", "AND", found.group(1)).strip())
    return expressions


def audit_text(text, *, project, new=False, filename="file.c", phase="preparation", baseline=None):
    """Return header findings; phase checking is separate from consent validation."""
    if project not in {"threadx", "docs", "local"} or phase not in {"preparation", "publication"}:
        raise ValueError("Unknown audit project or phase")
    header = leading_header(text)
    normalized = prose(header)
    findings = []
    copyrights = copyright_lines(header)
    if not copyrights or any(not re.fullmatch(r"Copyright\s+(?:\(c\)|©)\s+\S.*", item) for item in copyrights):
        findings.append("Missing or malformed leading copyright notice within sixty lines")
    new_ai = project == "threadx" and new and (Path(filename).suffix in {".c", ".S"} or Path(filename).name == "CMakeLists.txt")
    expected = "Apache-2.0 AND CC0-1.0" if project == "local" else "MIT AND CC0-1.0" if new_ai else "MIT"
    if spdx_expressions(header) != [expected]:
        findings.append("Expected exactly one SPDX-License-Identifier: " + expected)
    license_pattern = (r"https://www\.apache\.org/licenses/LICENSE-2\.0(?:\.txt)?(?=[\s.]|$)"
                       if project == "local" else r"https://opensource\.org/(?:licenses/MIT|license/mit)(?=[\s.]|$)")
    if not re.search(license_pattern, header):
        findings.append("Missing declared project license URL in leading header")
    if project == "local":
        if "Copyright (c) 2026 Eclipse SDV Hackathon Team" not in copyrights:
            findings.append("Local authored code requires the 2026 Eclipse SDV Hackathon Team copyright")
    if new_ai:
        if "Copyright (c) 2026 Eclipse ThreadX contributors" not in copyrights:
            findings.append("New ThreadX source requires the canonical 2026 contributor copyright")
        required = ["AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).",
                    "The AI-generated portions may be considered public domain (CC0-1.0)",
                    "and not subject to the project's licence."]
        for fragment in required:
            if fragment not in normalized:
                findings.append("Missing canonical new-file AI disclosure: " + fragment)
        pending = PENDING in normalized
        reviewed = REVIEWED in normalized
        if pending == reviewed or normalized.count(PENDING) > 1 or normalized.count(REVIEWED) > 1:
            findings.append("New-file disclosure must contain exactly one canonical pending or human-reviewed statement")
        elif phase == "publication" and pending:
            findings.append("Publication rejects pending human provenance review in new upstream files")
        if phase == "publication" and normalized.count(REVIEWED) != 1:
            findings.append("Publication requires the canonical human-reviewed statement exactly once")
    if project == "local":
        if "AI Disclosure:" not in normalized or "Codex (gpt-6.1-sol)" not in normalized or "AI-generated" not in normalized:
            findings.append("Local authored code requires Codex (gpt-6.1-sol) AI-generated disclosure")
        if PENDING not in normalized:
            findings.append("Local workflow/probe header must honestly retain pending human provenance review")
        if REVIEWED in normalized:
            findings.append("Local workflow/probe header must not assert upstream human review")
    if baseline is not None:
        before = leading_header(baseline)
        for original in copyright_lines(before):
            if original not in copyrights:
                findings.append("Removed or modified original copyright: " + original)
        for line in before.splitlines():
            marker = clean_line(line)
            if marker and ("AI assistance" in marker or "AI-generated" in marker or "AI Disclosure:" in marker):
                if marker not in [clean_line(candidate) for candidate in header.splitlines()]:
                    findings.append("Removed or modified original AI disclosure: " + marker)
    return findings


def git(repo, *args):
    result = subprocess.run(["git", *args], cwd=repo, capture_output=True, check=False)
    if result.returncode:
        raise RuntimeError("Git audit query failed: " + " ".join(args[:3]) + ": " + result.stderr.decode(errors="replace")[-1000:])
    return result.stdout


def changed_files(repo, base):
    committed = git(repo, "diff", "--name-only", "-z", base, "--")
    untracked = git(repo, "ls-files", "--others", "--exclude-standard", "-z")
    return sorted(set(item.decode() for item in (committed + untracked).split(b"\0") if item))


def baseline_text(repo, base, relative):
    found = git(repo, "ls-tree", "--name-only", "-z", base, "--", relative)
    if not found:
        return None
    return git(repo, "show", base + ":" + relative).decode()


def exemption(path):
    """Exclude copied/generated evidence by directory provenance, not extension."""
    for part in path.parts:
        if part in SNAPSHOT_PARTS:
            return "Retained upstream policy/source snapshot; preserve upstream provenance and notices"
        if (part in GENERATED_PARTS or part in {"build", "builds"}
                or part.startswith("build-") or part.startswith("build_") or part.endswith("-build")):
            return "Generated build/coverage/render output; preserve originating source provenance"
    return None


def is_code(path):
    return path.suffix in LOCAL_EXTENSIONS or path.name in LOCAL_FILENAMES


def file_record(path, relative, project, phase, new=False, baseline=None):
    record = {"path": str(path), "relative_path": str(relative), "project": project,
              "new": new, "status": "fail", "findings": []}
    if path.is_symlink():
        record["findings"] = ["Authored audit inputs may not redirect through symlinks"]
        return record
    try:
        data = path.read_bytes()
        record.update({"sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)})
        text = data.decode()
        record["spdx"] = spdx_expressions(leading_header(text))
        record["findings"] = audit_text(text, project=project, new=new, filename=path.name, phase=phase, baseline=baseline)
        record["status"] = "fail" if record["findings"] else "pass"
    except (OSError, UnicodeError) as error:
        record["findings"] = ["Missing, unreadable or non-text contribution source: " + str(error)]
    return record


def audit(source, docs, base, docs_base, workflow, artifacts, phase):
    report = {"status": "fail", "phase": phase, "policy_sources": POLICY_SOURCES,
              "scope": "Changed kernel/docs files, authored workflow code and retained local exploratory code",
              "files": [], "exemptions": [], "findings": [],
              "limitations": ["Header checks do not constitute human review, ECA verification or legal provenance attestation",
                              "Raw snapshots/generated outputs retain their originating project notices; they are not authored workflow sources"]}
    for repo, revision, project in [(source, base, "threadx"), (docs, docs_base, "docs")]:
        canonical_base = git(repo, "rev-parse", "--verify", revision + "^{commit}").decode().strip()
        report[project + "_base_sha"] = canonical_base
        report[project + "_tracked_patch_sha256"] = hashlib.sha256(git(repo, "diff", "--binary", canonical_base, "--")).hexdigest()
        paths = changed_files(repo, canonical_base)
        if not paths:
            report["findings"].append("No current " + project + " contribution files were found")
        for relative in paths:
            previous = baseline_text(repo, canonical_base, relative)
            report["files"].append(file_record(repo / relative, relative, project, phase,
                                                new=previous is None, baseline=previous))
    for root in [workflow, artifacts]:
        if not root.is_dir():
            report["findings"].append("Missing local audit root: " + str(root))
            continue
        for path in sorted(root.rglob("*")):
            if not path.is_file() or not is_code(path):
                continue
            relative = path.relative_to(root)
            reason = exemption(relative)
            if reason:
                data = path.read_bytes()
                report["exemptions"].append({"path": str(path), "reason": reason,
                                              "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)})
            else:
                report["files"].append(file_record(path, relative, "local", phase, new=True))
    # Retained policy snapshots live beside the artifact directory in the
    # contribution repository. Enumerate their original notices as exemptions.
    snapshots = artifacts.parent / "evidence" / "upstream-process"
    if snapshots.is_dir():
        for path in sorted(snapshots.rglob("*")):
            if path.is_file() and is_code(path):
                data = path.read_bytes()
                report["exemptions"].append({"path": str(path), "sha256": hashlib.sha256(data).hexdigest(),
                    "bytes": len(data), "reason": "Retained upstream policy/source snapshot; preserve upstream provenance and notices"})
    if not any(item["project"] == "local" and Path(item["path"]).is_relative_to(workflow) for item in report["files"]):
        report["findings"].append("No authored workflow code was found in the configured workflow root")
    counts = Counter(item["project"] for item in report["files"])
    report["counts"] = {"audited": len(report["files"]), "passed": sum(item["status"] == "pass" for item in report["files"]),
                        "failed": sum(item["status"] == "fail" for item in report["files"]),
                        "exemptions": len(report["exemptions"]), "by_project": dict(counts)}
    if not report["findings"] and report["files"] and not report["counts"]["failed"]:
        report["status"] = "pass"
    return report


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    for flag in ["source", "docs", "workflow", "artifacts"]:
        parser.add_argument("--" + flag, required=True, type=Path)
    for flag in ["base", "docs-base"]:
        parser.add_argument("--" + flag, required=True)
    parser.add_argument("--phase", choices=["preparation", "publication"], required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        report = audit(args.source, args.docs, args.base, args.docs_base, args.workflow, args.artifacts, args.phase)
    except (RuntimeError, OSError, UnicodeError, ValueError) as error:
        report = {"status": "fail", "phase": args.phase, "files": [], "exemptions": [], "counts": {}, "findings": [str(error)]}
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps({"status": report["status"], "counts": report["counts"], "output": str(args.output)}))
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
