#!/usr/bin/env python3
# Copyright (c) 2026 Eclipse SDV Hackathon Team
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).
# The AI-generated portions may be considered public domain (CC0-1.0).
# Human provenance review and verification are pending.
#
# SPDX-License-Identifier: Apache-2.0 AND CC0-1.0

"""Record actual approval/email messages against the existing native dossier.

The operator supplies the original user messages, never an invented REVIEWED
response. The reviewed immutable runner verifies its own evidence before the
receipt is written. This adapter neither finalizes source nor publishes a PR.
"""
import importlib.util
import json
from pathlib import Path
import re
import sys
import time

import fabro_control


def receipt_from_messages(messages, target, kernel_hash, docs_hash, question, run_id):
    if (not isinstance(messages, list) or len(messages) != 2
            or any(not isinstance(message, str) for message in messages)):
        raise RuntimeError("The two original human approval/email messages are required")
    if messages[0].strip().casefold() not in {"i agree", "i agree."}:
        raise RuntimeError("Missing explicit human agreement; automatic approval is invalid")
    email = re.fullmatch(r"(?:email is\s+)?([^\s@]+@[^\s@]+\.[^\s@]+)", messages[1].strip())
    if not email:
        raise RuntimeError("Missing the actual user's ECA commit email message")
    if (target.get("patch_sha256") != kernel_hash
            or target.get("docs_patch_sha256") != docs_hash):
        raise RuntimeError("The current patches differ from the agreed review dossier")
    if (question.get("stage") != "human_provenance" or not question.get("id")
            or question.get("review_target", {}).get("label")
            != "ThreadX #744: review patch " + kernel_hash):
        raise RuntimeError("The actual native human review question does not match this dossier")
    return {"confirmed": True, "reviewed_patch_sha256": kernel_hash,
            "patch_sha256": kernel_hash, "docs_patch_sha256": docs_hash,
            "author_email": email.group(1), "eclipse_username": "jnascimento6p0",
            "response": {"kind": "actual-user-conversation", "messages": messages},
            "native_run_id": run_id, "native_question_id": question["id"],
            "at": time.time(),
            "approved_delta": "Only canonical human-reviewed wording in the candidate new-file AI headers; final verification and independent review required"}


def record(input_path):
    supplied = json.loads(Path(input_path).read_text())
    binding = json.loads((fabro_control.ARTIFACTS / "execution-binding.json").read_text())
    bundle = Path(binding["bundle_path"])
    executions = fabro_control.STORE.parent / "executions"
    if (bundle.parent.resolve() != executions.resolve()
            or bundle.name != binding["bundle_sha256"] or bundle.is_symlink()):
        raise RuntimeError("Approval must use the recorded immutable execution bundle")
    spec = importlib.util.spec_from_file_location("reviewed_threadx_runner", bundle / "driver.py")
    runner = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(runner)
    runner.validate_execution_binding()
    active = fabro_control.request("/runs/" + supplied["run_id"])
    lifecycle = active["lifecycle"]["status"]
    if (lifecycle.get("kind") != "blocked"
            or lifecycle.get("blocked_reason") != "human_input_required"):
        raise RuntimeError("The reviewed native run is not waiting for human confirmation")
    runner.review_gate()
    target = runner.read("human-review-target.json")
    receipt = receipt_from_messages(supplied["messages"], target,
                                    runner.patch_hash(), runner.docs_hash(),
                                    active.get("current_question") or {}, supplied["run_id"])
    if (runner.EVIDENCE / "human-review.json").exists():
        raise RuntimeError("An existing human receipt must not be overwritten")
    runner.write("human-review-conversation.json", supplied)
    runner.write("human-review.json", receipt)
    print("Recorded original human agreement/email messages for", receipt["patch_sha256"])


if __name__ == "__main__":
    record(sys.argv[1])
