# Copyright (c) 2026 Eclipse SDV Hackathon Team
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).
# The AI-generated portions may be considered public domain (CC0-1.0).
# Human provenance review and verification are pending.
#
# SPDX-License-Identifier: Apache-2.0 AND CC0-1.0

"""Registered runs must reject later workspace or snapshot changes."""
import hashlib
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

import driver
import fabro_control


class ExecutionBindingTests(unittest.TestCase):
    def test_new_freeze_retires_prior_draft_and_mirrors_without_erasing_human_receipt(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            evidence, artifacts, history = root / "evidence", root / "artifacts", root / "history"
            evidence.mkdir()
            artifacts.mkdir()
            for directory in [evidence, artifacts]:
                (directory / "pr-body.md").write_text("old passing suite claim")
                (directory / "human-review-target.json").write_text("old target")
                (directory / "human-review.json").write_text("actual consent receipt")
            with patch.object(driver, "EVIDENCE", evidence), patch.object(driver, "REPO_ARTIFACTS", artifacts):
                driver.retire_prepared_outputs(history)
            self.assertFalse((evidence / "pr-body.md").exists())
            self.assertFalse((artifacts / "pr-body.md").exists())
            self.assertFalse((evidence / "human-review-target.json").exists())
            self.assertEqual((history / "pr-body.md").read_text(), "old passing suite claim")
            self.assertEqual((history / "artifact-mirrors/pr-body.md").read_text(), "old passing suite claim")
            self.assertEqual((evidence / "human-review.json").read_text(), "actual consent receipt")
            self.assertEqual((artifacts / "human-review.json").read_text(), "actual consent receipt")
            self.assertIn("superseded", (artifacts / "review.html").read_text())

    def test_registered_graph_executes_snapshot_and_ignores_later_workspace_edits(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            package = root / "workflow"
            package.mkdir()
            (package / "driver.py").write_text("original runner")
            (package / "Dockerfile").write_text("FROM example")
            (package / "workflow.fabro").write_text("python3 " + str(package / "driver.py") + " verify")
            (root / "regression-design.md").write_text("reviewed design")
            payloads = []
            with patch.object(fabro_control, "PACKAGE", package), \
                 patch.object(fabro_control, "STORE", root / "storage"), \
                 patch.object(fabro_control, "save"), \
                 patch.object(fabro_control, "request", side_effect=lambda path, payload: payloads.append(payload) or {"workflow_version_id": "version"}):
                fabro_control.register()
            graph = payloads[0]["files"]["workflow.fabro"]
            snapshot = Path(graph.split()[1])
            self.assertNotEqual(snapshot, package / "driver.py")
            (package / "driver.py").write_text("edited workspace runner")
            self.assertEqual(snapshot.read_text(), "original runner")
            with patch.object(driver, "PACKAGE", snapshot.parent):
                driver.validate_execution_binding()
                snapshot.chmod(0o644)
                snapshot.write_text("modified snapshot runner")
                with self.assertRaisesRegex(RuntimeError, "bundle changed"):
                    driver.validate_execution_binding()

    def test_changed_manifest_cannot_certify_changed_execution_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            hashes = {"driver.py": hashlib.sha256(b"original").hexdigest()}
            digest = hashlib.sha256(json.dumps(hashes, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
            bundle = Path(tmp) / digest
            bundle.mkdir()
            (bundle / "driver.py").write_text("replacement")
            hashes["driver.py"] = hashlib.sha256(b"replacement").hexdigest()
            (bundle / "execution-manifest.json").write_text(json.dumps({"files": hashes, "bundle_sha256": digest, "image_id": driver.IMAGE}))
            with patch.object(driver, "PACKAGE", bundle):
                with self.assertRaisesRegex(RuntimeError, "content-addressed"):
                    driver.validate_execution_binding()


if __name__ == "__main__":
    unittest.main()
