# Copyright (c) 2026 Eclipse SDV Hackathon Team
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).
# The AI-generated portions may be considered public domain (CC0-1.0).
# Human provenance review and verification are pending.
#
# SPDX-License-Identifier: Apache-2.0 AND CC0-1.0


"""Behavioral tests for contribution header, attribution and inventory gates."""
from pathlib import Path
import subprocess
import tempfile
import unittest

import license_audit as auditor


def header(project="threadx", state="pending", new=True):
    local = project == "local"
    owner = "Eclipse SDV Hackathon Team" if local else "Eclipse ThreadX contributors"
    expression = "Apache-2.0 AND CC0-1.0" if local else "MIT and CC0-1.0" if new else "MIT"
    url = "https://www.apache.org/licenses/LICENSE-2.0" if local else "https://opensource.org/licenses/MIT."
    provenance = auditor.PENDING if state == "pending" else auditor.REVIEWED
    return (f"/*\n * Copyright (c) 2026 {owner}\n * {url}\n"
            " * AI Disclosure: This file was largely AI-generated by Codex (gpt-6.1-sol).\n"
            " * The AI-generated portions may be considered public domain (CC0-1.0)\n"
            f" * and not subject to the project's licence. {provenance}\n"
            f" * SPDX-License-Identifier: {expression}\n */\n")


class HeaderTests(unittest.TestCase):
    def check(self, text, **kwargs):
        return auditor.audit_text(text, project=kwargs.pop("project", "threadx"), new=kwargs.pop("new", True), **kwargs)

    def test_pending_upstream_header_passes_preparation_but_not_publication(self):
        self.assertEqual(self.check(header()), [])
        self.assertTrue(self.check(header(), phase="publication"))

    def test_canonical_upstream_header_is_required_for_publication(self):
        self.assertEqual(self.check(header(state="reviewed"), phase="publication"), [])
        malformed = header(state="reviewed").replace(auditor.REVIEWED, "An agent reviewed and certified everything.")
        self.assertTrue(self.check(malformed, phase="publication"))

    def test_conflicting_pending_and_reviewed_claims_are_rejected(self):
        text = header().replace(auditor.PENDING, auditor.PENDING + " " + auditor.REVIEWED)
        self.assertTrue(self.check(text))

    def test_duplicate_human_review_statements_are_rejected(self):
        for state, phrase in [("pending", auditor.PENDING), ("reviewed", auditor.REVIEWED)]:
            with self.subTest(state=state):
                self.assertTrue(self.check(header(state=state).replace(phrase, phrase + " " + phrase)))

    def test_missing_wrong_or_duplicate_license_identifier_is_rejected(self):
        for change in ["", "SPDX-License-Identifier: EPL-2.0", "SPDX-License-Identifier: MIT OR CC0-1.0",
                       "SPDX-License-Identifier: MIT and CC0-1.0\n * SPDX-License-Identifier: MIT"]:
            with self.subTest(change=change):
                self.assertTrue(self.check(header().replace("SPDX-License-Identifier: MIT and CC0-1.0", change)))

    def test_missing_copyright_license_url_or_model_attribution_is_rejected(self):
        for value in ["Copyright (c) 2026 Eclipse ThreadX contributors", "https://opensource.org/licenses/MIT.", "Codex (gpt-6.1-sol)"]:
            with self.subTest(value=value):
                self.assertTrue(self.check(header().replace(value, "")))

    def test_license_text_after_code_or_sixty_lines_cannot_fake_a_header(self):
        self.assertTrue(self.check("int main(void) { return 0; }\n" + header()))
        self.assertTrue(self.check("\n" * 60 + header()))

    def test_hash_comment_cmake_header_and_assembly_follow_same_new_file_policy(self):
        hashed = "\n".join("# " + auditor.clean_line(line) for line in header().splitlines())
        self.assertEqual(self.check(hashed + "\ncmake_minimum_required(VERSION 3.13)", filename="CMakeLists.txt"), [])
        self.assertEqual(self.check(header(), filename="entry.S"), [])

    def test_original_copyright_and_disclosure_cannot_be_removed_or_modified(self):
        original = ("/*\n * Copyright (c) 2024 Microsoft Corporation\n * https://opensource.org/licenses/MIT.\n"
                    " * SPDX-License-Identifier: MIT\n */\n// Portions of this file were generated with AI assistance.\n")
        candidate = original.replace(" * SPDX", " * Copyright (c) 2026 Eclipse ThreadX contributors\n * SPDX")
        self.assertEqual(self.check(candidate, new=False, baseline=original), [])
        for value in ["Copyright (c) 2024 Microsoft Corporation", "Portions of this file were generated with AI assistance."]:
            self.assertTrue(self.check(candidate.replace(value, "Removed notice"), new=False, baseline=original))

    def test_existing_ascii_doc_mit_header_accepts_its_original_license_url(self):
        text = "////\n Copyright (c) Microsoft\n https://opensource.org/license/mit.\n SPDX-License-Identifier: MIT\n////\n= Chapter\n"
        self.assertEqual(self.check(text, project="docs", new=False), [])

    def test_local_pending_header_remains_valid_in_both_phases(self):
        for phase in ["preparation", "publication"]:
            self.assertEqual(self.check(header(project="local"), project="local", phase=phase), [])
        self.assertTrue(self.check(header(project="local", state="reviewed"), project="local"))


class InventoryTests(unittest.TestCase):
    def repository(self, root, name):
        repo = root / name
        repo.mkdir()
        for args in [["init", "-q"], ["config", "user.email", "synthetic@example.com"], ["config", "user.name", "Synthetic fixture"]]:
            subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True)
        (repo / "existing.c").write_text(header(new=False))
        subprocess.run(["git", "add", "."], cwd=repo, check=True, capture_output=True)
        subprocess.run(["git", "commit", "-qm", "Synthetic test baseline"], cwd=repo, check=True, capture_output=True)
        (repo / "existing.c").write_text(header(new=False) + "int fixture;\n")
        return repo

    def test_inventory_includes_untracked_source_and_authored_probe_and_enumerates_generated_exemptions(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = self.repository(root, "source")
            docs = self.repository(root, "docs")
            (source / "new.c").write_text(header())
            workflow, artifacts = root / "workflow", root / "artifacts"
            workflow.mkdir(); artifacts.mkdir()
            (workflow / "runner.py").write_text(header(project="local"))
            probe = artifacts / "exploratory-probe" / "probe.c"
            probe.parent.mkdir(); probe.write_text(header(project="local"))
            generated = artifacts / "diagnostics" / "baseline-build" / "regression" / "copied.c"
            generated.parent.mkdir(parents=True); generated.write_text("int generated;\n")
            report = auditor.audit(source, docs, "HEAD", "HEAD", workflow, artifacts, "preparation")
            self.assertEqual(report["status"], "pass", report)
            self.assertEqual(report["counts"]["audited"], 5)
            self.assertEqual(report["counts"]["exemptions"], 1)
            self.assertTrue(all(record.get("sha256") for record in report["files"]))
            probe.write_text("int missing_header;\n")
            self.assertEqual(auditor.audit(source, docs, "HEAD", "HEAD", workflow, artifacts, "preparation")["status"], "fail")

    def test_invalid_git_base_does_not_emit_success(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            output = root / "report.json"
            result = auditor.main(["--source", str(root), "--docs", str(root), "--base", "missing", "--docs-base", "missing",
                                   "--workflow", str(root), "--artifacts", str(root), "--phase", "preparation", "--output", str(output)])
            self.assertEqual(result, 1)
            self.assertIn('"status": "fail"', output.read_text())

    def test_symlinked_authored_source_cannot_redirect_inventory(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            target = root / "target.c"; target.write_text(header())
            link = root / "linked.c"; link.symlink_to(target)
            self.assertEqual(auditor.file_record(link, "linked.c", "threadx", "preparation", new=True)["status"], "fail")


if __name__ == "__main__":
    unittest.main()
