# SPDX-License-Identifier: Apache-2.0
# Generated layout: compiles upstream inc_diagnostics sources in place with Cargo.
[package]
name = "sovd_adapter"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "../../../../upstream/inc_diagnostics-pr6/score/mw/diag/sovd_adapter/lib.rs"

[dependencies]
diag_api = { path = "../diag_api" }
opensovd-core = { git = "https://github.com/eclipse-opensovd/opensovd-core.git", rev = "0cb4b250643164d678389385aa94b6a92bb7f0c7" }
async-trait = "0.1.89"
indexmap = "2.11"
serde_json = "1"
diag_json = { path = "../diag_json" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
