[package]
name = "simple_operation"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "../../../inc/score/mw/diag/api/simple_operation.rs"

[dependencies]
common = { path = "../common" }
operation = { path = "../operation" }
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
