# SPDX-License-Identifier: Apache-2.0
# Cruise control diagnostics: diag_api DataResources behind a CruiseLink.
[package]
name = "cruise_diag"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
diag_api = { path = "../diag_api" }
diag_json = { path = "../diag_json" }
sovd_adapter = { path = "../sovd_adapter" }
