#!/usr/bin/env bash

# ctl.sh for the OpenSOVD vECU — wrapper for docker compose to ease bringing
# the diagnostics stack up/down, plus auto-opening the SOVD Adapter Console in
# the browser, like the other vECU control scripts (vecu/ota/ctl.sh).
#
#   opensovd-gateway       inc_diagnostics PR #40 gateway, component `cruise`   :7690
#   sovd-adapter-console   ../SOVD_Adapter_Console (Zenoh vehicle + SOVD + CDA) :8080
#   CDA + ECU simulator    upstream classic-diagnostic-adapter testcontainer    :20002 / :8181
#
# See also https://docs.docker.com/compose/

set -euo pipefail

# Check if the script is being sourced.
if ( return 0 2>/dev/null ); then
  echo -e "\033[1;33mThis script is not meant to be sourced.\033[0m"
  exit 1
fi

# This folder holds docker-compose.yaml and gateway/; the console sources are
# in ../SOVD_Adapter_Console, so compose resolves all relative paths from here
# regardless of the directory ctl.sh is called from.
OPENSOVD_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "$OPENSOVD_DIR/../.." && pwd)"   # the X-Verse checkout holding external_hackathon_ecus/

CONSOLE_URL="http://localhost:${CONSOLE_PORT:-8080}"

# Classic path: the upstream CDA test containers (ECU simulator + CDA), pinned
# at c1a5d8b. OPENSOVD_CDA=0 leaves it out (the console then shows the
# CDA and the simulator as down; the SOVD side is unaffected).
# Default: the checkout's upstream/ clone when there is one,
# else a private clone in .local/ (ignored by git).
if [[ -z "${CDA_DIR:-}" ]]; then
  CDA_DIR="$ROOT_DIR/upstream/classic-diagnostic-adapter"
  [[ -d "$CDA_DIR" ]] || CDA_DIR="$OPENSOVD_DIR/.local/classic-diagnostic-adapter"
fi
CDA_REPO="https://github.com/eclipse-opensovd/classic-diagnostic-adapter.git"
CDA_PIN="c1a5d8b223fc32c84bfbab8122a709a75280a821"
CDA_ENABLED="${OPENSOVD_CDA:-1}"

COMMAND="${1:-}"

usage() {
  cat <<EOF
Usage: $0 <command>
Wrapper for docker compose to simplify managing the OpenSOVD vECU
(opensovd-gateway :7690 + SOVD Adapter Console :8080 + CDA :20002 / ECU simulator :8181).

Commands:
  build   Build (or refresh) all images without starting anything; used by
          setup.sh so the first up does not have to compile (gateway ~2 min,
          CDA ~15 min, longer than run_autoverse.py waits for a step).
  up      Build (cached) if needed, create and start all containers,
          then open the SOVD Adapter Console (${CONSOLE_URL}) in the browser.
          The first build compiles the gateway and the CDA (several minutes).
  stop    Stop running containers without removing them.
  start   Resume containers previously stopped by stop (or run up when they
          do not exist yet), then open the console in the browser.
  down    Stop and remove the containers (images kept).
  logs    Follow the gateway + console logs.
  check   Run the console's 13 checks inside the console container.
  help    Show this help message.

Environment:
  OPENSOVD_CDA=0                 leave the CDA + ECU simulator out
  CDA_DIR=<path>                 classic-diagnostic-adapter checkout (cloned at ${CDA_PIN:0:8} if missing)
  CRUISE_DEBOUNCE_FAILED_MS / CRUISE_DEBOUNCE_PASSED_MS   gateway debounce (demo 1500 / 1000)
  OPENSOVD_BROWSER=0             do not open the browser

Examples:
  $0 build
  $0 up
  $0 stop
  $0 start
  $0 down
  $0 check
EOF
  exit 0
}

log() { echo "[opensovd] $*"; }

compose()     { docker compose --project-directory "$OPENSOVD_DIR" -f "$OPENSOVD_DIR/docker-compose.yaml" "$@"; }
cda_compose() { SIM_CONTROL_PORT=8181 CDA_PORT=20002 docker compose -f "$CDA_DIR/testcontainer/docker-compose.yml" "$@"; }

# ---------------------------------------------------------------- CDA checkout

ensure_cda() {
    [[ "$CDA_ENABLED" == "0" ]] && return 1
    if [[ ! -f "$CDA_DIR/testcontainer/docker-compose.yml" ]]; then
        log "cloning classic-diagnostic-adapter @ ${CDA_PIN:0:8} into $CDA_DIR ..."
        git clone -q "$CDA_REPO" "$CDA_DIR"
        git -C "$CDA_DIR" checkout -q "$CDA_PIN"
    fi
    # Normally generated by the upstream integration tests; a copy avoids needing them.
    if [[ ! -f "$CDA_DIR/testcontainer/cda-test-config.toml" ]]; then
        cp "$OPENSOVD_DIR/cda/cda-test-config.toml" "$CDA_DIR/testcontainer/cda-test-config.toml"
    fi
    return 0
}

# ---------------------------------------------------------------- browser

# Same pattern as vecu/ota/ctl.sh open_browser(): wait for the console to
# answer, then launch a browser.
open_browser() {
    local timeout="${OPENSOVD_BROWSER_WAIT_S:-120}" waited=0
    echo "Waiting for the SOVD Adapter Console to respond (${CONSOLE_URL})..."
    until curl -s -o /dev/null --max-time 3 "$CONSOLE_URL/api/config"; do
        if (( waited >= timeout )); then
            echo "Console not reachable after ${timeout}s — open manually: $CONSOLE_URL"
            return 0
        fi
        sleep 2; waited=$((waited + 2))
    done
    echo "SOVD Adapter Console: $CONSOLE_URL"

    if [[ "${OPENSOVD_BROWSER:-1}" == "0" ]]; then
        return 0
    fi
    if [[ -z "${DISPLAY:-}" && -z "${WAYLAND_DISPLAY:-}" ]]; then
        echo "No graphical display — open manually: $CONSOLE_URL"
        return 0
    fi

    DEFAULT_BROWSER=$(xdg-settings get default-web-browser 2>/dev/null || true)

    # Detach the browser (own session, no inherited stdio) so it outlives
    # this script and the run_autoverse.py process group that launched it.
    launch() { setsid -f "$@" "$CONSOLE_URL" < /dev/null &> /dev/null; }

    echo "Launching browser..."
    if [[ "$DEFAULT_BROWSER" == *"chrome"* || "$DEFAULT_BROWSER" == *"google"* ]] \
            && command -v google-chrome &> /dev/null; then
        launch google-chrome --new-window
    elif [[ "$DEFAULT_BROWSER" == *"firefox"* ]] && command -v firefox &> /dev/null; then
        launch firefox --new-window
    elif command -v google-chrome &> /dev/null; then
        launch google-chrome --new-window
    elif command -v xdg-open &> /dev/null; then
        launch xdg-open
    else
        echo "No known browser found — open manually: $CONSOLE_URL"
    fi
}

# ---------------------------------------------------------------- actions

do_build() {
    if ensure_cda; then
        log "building the CDA + ECU simulator images ..."
        cda_compose build
    else
        log "CDA + ECU simulator left out (OPENSOVD_CDA=0)"
    fi
    log "building the opensovd-gateway + SOVD Adapter Console images ..."
    compose build
}

do_up() {
    if ensure_cda; then
        log "building (cached layers) + starting the CDA + ECU simulator ..."
        cda_compose up -d
    else
        log "CDA + ECU simulator left out (OPENSOVD_CDA=0)"
    fi
    log "building (cached layers) + starting opensovd-gateway + SOVD Adapter Console ..."
    compose up -d --build
    echo "stack is up:"
    docker ps --filter name=opensovd-gateway --filter name=sovd-adapter-console \
        --filter name=testcontainer- --format '{{.Names}}\t{{.Status}}'
    open_browser
}

do_stop() {
    log "stopping containers (kept on disk) ..."
    compose stop
    if [[ "$CDA_ENABLED" != "0" && -f "$CDA_DIR/testcontainer/docker-compose.yml" ]]; then
        cda_compose stop
    fi
}

do_start() {
    if ! docker container inspect opensovd-gateway sovd-adapter-console &> /dev/null; then
        echo "Containers not created yet. Running up ..."
        do_up
        return 0
    fi
    log "starting previously created containers ..."
    if [[ "$CDA_ENABLED" != "0" && -f "$CDA_DIR/testcontainer/docker-compose.yml" ]]; then
        cda_compose start
    fi
    compose start
    open_browser
}

do_down() {
    log "removing containers (images kept) ..."
    compose down
    if [[ "$CDA_ENABLED" != "0" && -f "$CDA_DIR/testcontainer/docker-compose.yml" ]]; then
        cda_compose down
    fi
}

do_logs() {
    compose logs -f opensovd-gateway sovd-adapter-console
}

do_check() {
    docker exec sovd-adapter-console python runner.py "${@}"
}

case "${COMMAND}" in
    build) do_build ;;
    up)    do_up ;;
    stop)  do_stop ;;
    start) do_start ;;
    down)  do_down ;;
    logs)  do_logs ;;
    check) do_check "${@:2}" ;;
    help|--help|-h|"") usage ;;
    *) echo "Unknown command: ${COMMAND}"; usage ;;
esac

echo "Done"
