[package]
name = "diag_api"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "../../../inc/score/mw/diag/api/diag_api.rs"

[dependencies]
common = { path = "../common" }
data_resource = { path = "../data_resource" }
operation = { path = "../operation" }
simple_operation = { path = "../simple_operation" }
uds = { path = "../uds" }
uds_adapters = { path = "../uds_adapters" }
