# SPDX-License-Identifier: Apache-2.0
# Cruise control on the S-CORE path (EclipseHackthon2026 demo).
# Built inside eclipse-score/inc_someip_gateway, so it uses the same pinned
# mw::com (score_communication) as gatewayd. demo/score/build.sh links it in.

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")
load("//bazel/tools:someip_config.bzl", "generate_someip_config_bin")

cc_library(
    name = "cruise_types",
    hdrs = ["cruise_types.h"],
    deps = [
        "//score/serializer:pre_serialized_data",
        "@score_communication//score/mw/com",
    ],
)

cc_library(
    name = "cruise_api_cpp",
    srcs = ["cruise_api.cpp"],
    implementation_deps = [
        "@score_communication//score/mw/com/rust/score_com_cpp_bridge:register_interface",
    ],
    deps = [":cruise_types"],
    alwayslink = True,
)

rust_library(
    name = "cruise_api",
    srcs = ["cruise_api.rs"],
    features = ["link_std_cpp_lib"],
    deps = [
        ":cruise_api_cpp",
        "@score_communication//score/mw/com/rust:score_com",
    ],
)

rust_test(
    name = "cruise_api_test",
    crate = ":cruise_api",
    features = ["link_std_cpp_lib"],
)

rust_binary(
    name = "cruise_bridge",
    srcs = ["cruise_bridge.rs"],
    features = ["link_std_cpp_lib"],
    deps = [
        ":cruise_api",
        "@score_communication//score/mw/com/rust:score_com",
    ],
)

cc_binary(
    name = "cruise_ecu",
    srcs = ["cruise_ecu.cpp"],
    deps = ["@vsomeip"],
)

generate_someip_config_bin(
    name = "vehicle_config",
    json = "config/vehicle_someip_config.json",
    output = "vehicle_someip_config.bin",
)
