' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!startsub ConfigProviderFactory
namespace score::config_management::config_provider {
class ConfigProviderFactory {
    + Create(\n\
    token : score::cpp::stop_token,\n\
    timeout : std::chrono::milliseconds,\n\
    max_samples_limit : score::cpp::optional<std::size_t>,\n\
    polling_cycle_interval : score::cpp::optional<std::chrono::milliseconds>,\n\
    memory_resource : score::cpp::pmr::memory_resource* const,\n\
    callback : IsAvailableNotificationCallback&&) : score::cpp::pmr::unique_ptr<ConfigProvider>
    + Create(\n\
    token : score::cpp::stop_token,\n\
    persistency : score::cpp::pmr::unique_ptr<Persistency>,\n\
    max_samples_limit : score::cpp::optional<std::size_t>,\n\
    polling_cycle_interval : score::cpp::optional<std::chrono::milliseconds>,\n\
    memory_resource : score::cpp::pmr::memory_resource* const,\n\
    callback : IsAvailableNotificationCallback&&) : score::cpp::pmr::unique_ptr<ConfigProvider>
    + Create(\n\
    token : score::cpp::stop_token ,\n\
    timeout : std::chrono::milliseconds ,\n\
    memory_resource : score::cpp::pmr::memory_resource* const ,\n\
    callback : IsAvailableNotificationCallback&&) : score::cpp::pmr::unique_ptr<ConfigProvider>
    + Create(\n\
    token : score::cpp::stop_token,\n\
    persistency : score::cpp::pmr::unique_ptr<Persistency>,\n\
    memory_resource : score::cpp::pmr::memory_resource* const,\n\
    callback : IsAvailableNotificationCallback&&) : score::cpp::pmr::unique_ptr<ConfigProvider>
    --
    - logger_ : mw::log::Logger&
    --
    Responsibility: This class is responsible to create ConfigProvider class
}
}
!endsub

@enduml
