#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Prepares a fresh laptop for the demo. Idempotent; safe to re-run.
#
#   1. clones the upstream repositories at the pinned commits into upstream/
#   2. checks out inc_diagnostics PR #6 and applies our patch series on top
#   3. builds the CDA + ECU simulator images and the demo gateway
#
# Needs: git, docker (compose v2), cargo, curl, jq, bc. OpenSSL headers
# (libssl-dev) only for the upstream CDA integration tests.

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
UP=$ROOT/upstream
PR6_HEAD=b975ed410198a6980c8ab249b550c5e21e35e648
CDA_PIN=c1a5d8b223fc32c84bfbab8122a709a75280a821
BRANCH=feat/16-sovd-data-provider

step() { printf '\n==> %s\n' "$*"; }
mkdir -p "$UP"

step "classic-diagnostic-adapter @ ${CDA_PIN:0:8}"
if [[ ! -d $UP/classic-diagnostic-adapter/.git ]]; then
    git clone -q https://github.com/eclipse-opensovd/classic-diagnostic-adapter.git "$UP/classic-diagnostic-adapter"
fi
git -C "$UP/classic-diagnostic-adapter" fetch -q origin "$CDA_PIN" 2>/dev/null || true
git -C "$UP/classic-diagnostic-adapter" checkout -q "$CDA_PIN"

step "inc_diagnostics PR #6 @ ${PR6_HEAD:0:8} + our patches"
if [[ ! -d $UP/inc_diagnostics/.git ]]; then
    git clone -q https://github.com/eclipse-score/inc_diagnostics.git "$UP/inc_diagnostics"
fi
git -C "$UP/inc_diagnostics" fetch -q origin pull/6/head:pr-6 2>/dev/null || git -C "$UP/inc_diagnostics" fetch -q origin "$PR6_HEAD"
if [[ ! -d $UP/inc_diagnostics-pr6 ]]; then
    git -C "$UP/inc_diagnostics" worktree add -q "$UP/inc_diagnostics-pr6" "$PR6_HEAD"
fi
cd "$UP/inc_diagnostics-pr6"
if git rev-parse -q --verify "$BRANCH" > /dev/null; then
    echo "branch $BRANCH exists - leaving it as is"
    git checkout -q "$BRANCH"
else
    git checkout -q -b "$BRANCH" "$PR6_HEAD"
    git -c user.name="demo setup" -c user.email=demo@localhost am -q "$ROOT"/contrib/inc_diagnostics/*.patch
fi
git log --oneline "$PR6_HEAD..HEAD"

step "CDA + ECU simulator images (first run takes several minutes)"
cd "$UP/classic-diagnostic-adapter/testcontainer"
# Normally generated by the upstream integration tests; a copy avoids needing them.
[[ -f cda-test-config.toml ]] || cp "$ROOT/demo/cda/cda-test-config.toml" cda-test-config.toml
docker compose build

step "demo gateway (Cargo)"
cd "$ROOT/demo/gateway"
cargo build --bin opensovd-gateway

step "done - next: demo/start.sh, then demo/run-demo.sh"
