' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!startsub ConfigProviderError
namespace score::config_management::config_provider {
enum ConfigProviderError {
    kParsingFailed
    kObjectCastingError
    kParameterNotFound
    kValueCastingError
    kValueNotFound
    kProxyNotReady
    kProxyAccessTimeout
    kProxyReturnedNoResult
    kEmptyCallbackProvided
    kCallbackAlreadySet
    kMethodNotSupported
    kFailedToSubscribe
    kParameterSetNotFound
}
}
!endsub

@enduml
