[serial]
port = "/dev/ttyACM0"
baudrate = 115200
write_byte_delay = 0.01
send_command_expected = "Console command succeeded"
send_command_timeout = 0.1
send_command_max_retries = 2

[eth]
ip_address = "192.168.0.200"

[freertos.target_process]
command_line = "/media/jefferson/11c42dee-73a3-4c2b-ab42-a0440011d9e0/openbsw-sil/tools/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gdb -batch -x reset.gdb /media/jefferson/11c42dee-73a3-4c2b-ab42-a0440011d9e0/openbsw-sil/openbsw/build/s32k148-freertos/executables/referenceApp/application/RelWithDebInfo/app.referenceApp.elf > /dev/null 2>&1"
wait_for_exit = true
skip_first = false

[boot]
started_str = "INFO: Run level 1"
complete_str = "DEBUG: Run level 9 done"
max_time = 1.5
